### ISSUE TITLE
Possible issue with exponential filtering

### ISSUE THREAD

**Issue by slifer50** [climate-machine/CLIMA#1003]
# Description

Using the exponential filter particularly for lower order filters seems to generate some element imprinting. Here are some figures describing what I've observed comparing unfiltered to filtered momentum fields for filters of order 6, 10 and 14 respectively:
<img width="577" alt="Screen Shot 2020-04-24 at 3 28 17 PM" src="https://user-images.githubusercontent.com/54990670/80250946-c1773500-8642-11ea-8fd3-b393381d2bef.png">
<img width="577" alt="Screen Shot 2020-04-24 at 3 27 49 PM" src="https://user-images.githubusercontent.com/54990670/80250953-c3d98f00-8642-11ea-9237-be57fc38b119.png">
<img width="577" alt="Screen Shot 2020-04-24 at 3 28 05 PM" src="https://user-images.githubusercontent.com/54990670/80250957-c5a35280-8642-11ea-8490-7175d6b9e1f1.png">
@lcw @akshaysridhar 

## Steps to reproduce
Here is the file and where I define the filter callback:
https://github.com/climate-machine/CLIMA/blob/d4963da5228c536f40e1e8337b8afd32ab2dca6b/experiments/AtmosLES/tropical_cyclone_dry_walls.jl#L374

**Comment by lcw** [comment]
The exponential filter works element-by-element so if you turn up the filter by decreasing the filter order it can introduce discontinuities between elements.

**Comment by slifer50** [comment]
Thanks for the explanation @lcw, I wanted to make sure this was expected behaviour. I'll close the since it seems to be what we can expect to see.
