### ISSUE TITLE
1D integrals for simple radiation are not actually integrals (it seems)

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#1009]
https://github.com/climate-machine/CLIMA/blob/d932dc59e793e63fe96f60c06507df9698fcc5d9/experiments/AtmosLES/dycoms.jl#L117

https://github.com/climate-machine/CLIMA/blob/d932dc59e793e63fe96f60c06507df9698fcc5d9/experiments/AtmosLES/dycoms.jl#L113

It seems that the column integrals defined here are actually never integrated. For example, line 117 above assigns the value of line 113 to it, but without actually calculating the 1D integral along the column.
For example,  the vtk plot is showing what the quantity `∫dz.radiation.attenuation_coeff`, which is wrong since it is not z-integrated.

![image](https://user-images.githubusercontent.com/46322845/80310152-3b283380-87a7-11ea-9184-b52363de32c4.png)

@akshaysridhar

**Comment by akshaysridhar** [comment]
The cloud layer is order(100m) deep, \kappa is order(10), \rho is order(1) and q_liq is order(10^-4). This means the integrand is expected to be of order(10^-1). An alternative diagnostic (perhaps one that is more intuitive) to this is to visualize the actual flux term if necessary (F0 exp(-Q0(z)) + F1 exp(-Q1(z)) + F3(z)).

**Comment by smarras79** [comment]
> The cloud layer is order(100m) deep, \kappa is order(10), \rho is order(1) and q_liq is order(10^-4). This means the integrand is expected to be of order(10^-1). An alternative diagnostic (perhaps one that is more intuitive) to this is to visualize the actual flux term if necessary (F0 exp(-Q0(z)) + F1 exp(-Q1(z)) + F3(z)). If the value being returned was simply the integrand at each z level , its order of magnitude would be (at most) 10^-3. Maybe the variable naming is the source of confusion (?)

Regardless of the value, the quantity in the plot changes along z, which should not if it is an integral along z. 
The `integrand` in the code is never integrated along z. The quantities Q0(z) and Q1(z) in the formula that you posted are not a function of z but an integral along z, hence making Q0 and Q1 constant in each column.

Is the actual integration operation missing in the code or is it done somewhere else? 
What is written to file are the `integrands` and not the `integrals`.

**Comment by charleskawczynski** [comment]
@smarras79 this is an indefinite stack integral, so it is a function of `z` perhaps you’re just interested in the value at `z=z_max`.

**Comment by charleskawczynski** [comment]
That said, it might be nice to offer definite integral support, but this will probably be more natural to add once we have planar `auxstate`s

**Comment by smarras79** [comment]
> @smarras79 this is an indefinite stack integral, so it is a function of `z` perhaps you’re just interested in the value at `z=z_max`.

That's the problem, it needs to be a definite integral between 0 and zmax split in the two integrals called Q1, Q2 in the code. 

We are calculating the expression above which used to be done correctly. I don't know how the integrals are done in the new version. Thanks @charleskawczynski
