### ISSUE TITLE
Issue with formatter

### ISSUE THREAD

**Issue by skandalaCLIMA** [climate-machine/CLIMA#1013]
# Description

The formatter (run on the local computer) seems to format the code in a way that fails the github format check. Manually formatting it in the recommended format fixes the issues. However, it breaks down everytime the formatter is applied again on the local computer.

## Steps to reproduce

1. Running formatter on the local computer using ```julia .dev/format.jl ```

## Expected behavior

Once formatter is applied locally, it should pass the formatting check on github. However, this is not happening in some cases.

## Screenshots
<img width="1189" alt="Screen Shot 2020-04-27 at 9 42 16 AM" src="https://user-images.githubusercontent.com/55154978/80398369-590b9c00-886c-11ea-8980-3f96d77ed163.png">

## Environment and error messages

```julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_MPI_PATH = /usr/local/opt/mpich
  JULIA_MPI_INCLUDE_PATH = /usr/local/include
  JULIA_MPI_LIBRARY_PATH = /usr/local/lib```

## Additional context



<!--- Please leave the following section --->

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by charleskawczynski** [comment]
@skandalaCLIMA I'm not able to reproduce this locally. Everything seemed to work when I applied the formatter.

**Comment by simonbyrne** [comment]
@skandalaCLIMA What does `julia --project=.dev -e 'using Pkg; Pkg.status()'` give?

**Comment by skandalaCLIMA** [comment]
```(base) Sriharshas-MacBook-Pro:CLIMA sriharshakandala$ julia --project=.dev -e 'using Pkg; Pkg.status()'
Status `~/work/CLIMA/.dev/Project.toml`
  [98e50ef6] JuliaFormatter v0.3.6
(base) Sriharshas-MacBook-Pro:CLIMA sriharshakandala$ ```

**Comment by simonbyrne** [comment]
Try running
```
 julia --project=.dev -e 'using Pkg; Pkg.update()'
```
and then rerun the formatter.

**Comment by skandalaCLIMA** [comment]
This is working.
