### ISSUE TITLE
Variable name convention list

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#116]
I think that it would be a good idea to start making a master list for variable names and their definition.

I'd like to get something up on the wall so that everyone has a common reference. I'd definitely like to hear people weigh in. @simonbyrne, @lcw @jkozdon @ali-ramadhan

Technically, the design docs should address this issue, however, we've perhaps limited ourselves by only allowing lowercase variables in our [CodingConventions](https://github.com/climate-machine/CLIMA/blob/master/docs/src/CodingConventions.md). We've started violating these naming conventions (for example [here](https://github.com/climate-machine/CLIMA/blob/master/src/ClimaAtmos/Dycore/drivers/rising_thermal_bubble.jl#L62)). I've done this myself [here](https://github.com/climate-machine/CLIMA/blob/master/src/ClimaAtmos/Parameterizations/SurfaceFluxes/src/SurfaceFluxes.jl#L265).

Perhaps this should be two issues, but I think that we should
 - Develop a master variable name list
 - Update the coding conventions such that they can be followed

I don't mean to harp on this issue. I just think that if we don't put in the effort to maintain/improve our naming conventions as we go, it will most certainly get worse.

**Comment by ali-ramadhan** [comment]
Thanks for bringing this up. Is this to keep a consistent mapping between physical variables (e.g. _temperature_ and _gravitational acceleration_) and variables in the code (e.g. `T` and `g`)?

I agree that having some uppercase variables would really help with readability, e.g. temperature `T` or salinity `S`.

Would it be helpful if we maintained a list of variables for the ocean? Would probably be good to agree on common variables.

We can also adopt something like [PlanetParameters.jl](https://github.com/climate-machine/CLIMA/blob/master/src/PlanetParameters/src/PlanetParameters.jl) although we'd like to be able to change the planetary parameters in case we want to e.g. vary the Earth's rotation rate or model an ocean on Europa, etc.

**Comment by charleskawczynski** [comment]
Yes, I agree that we should update [CodingConventions](https://github.com/climate-machine/CLIMA/blob/master/docs/src/CodingConventions.md) to permit upper-case characters.

@asraero has done great work on making a comprehensive and descriptive [list](https://github.com/climate-machine/CLIMA/pull/138/files#diff-7c7f617b2d7d3c148d33090c93acd685) of variable names which, in itself, nearly nullifies my concerns. In addition, some naming issues that I was running into will be addressed if #147 works out (I really didn't want to make a function called `saturation_adjustment_for_shum_and_liquid_potential_temperature`).

**Comment by asraero** [comment]
We've begun to address this issue in : https://github.com/climate-machine/CLIMA/blob/master/docs/src/VariableList.md
