### ISSUE TITLE
Possible error in Prandtl value

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#118]
Before I change it  and affect everybody else, I believe there is a mistake in the value of 

`@parameter  prandtl 71//10`  in `VanillaAtmosDistrectizations.jl`

which should be 

`@parameter  prandtl 71//100`

**Comment by lcw** [comment]
Could be I copied the value from Canary https://github.com/climate-machine/Canary.jl/blob/master/examples/3d_kernels/nse3d.jl#L129 so that it reproduced the nse3d example results.

**Comment by smarras79** [comment]
> Could be I copied the value from Canary https://github.com/climate-machine/Canary.jl/blob/master/examples/3d_kernels/nse3d.jl#L129 so that it reproduced the nse3d example results.

Good to know. I will fix it then. Thanks.
