### ISSUE TITLE
Need more MoistThermo conversion functions

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#119]
To get Bomex running, we need several more MoistThermodynamics conversion functions:

 - A saturation adjustment for liquid potential temperature
 - All of the functions needed for the liquid potential temperature saturation adjustment
 - A function to compute density potential temperature

**Comment by tapios** [comment]
Why saturation adjustment for liquid potential temperature? I would just convert the initial condition given in liquid potential temperature (and any relaxation terms involving liquid potential energy) to internal energy and work with that.

**Comment by charleskawczynski** [comment]
In Bomex, and several other cases, `q_t` and `\theta_l` are given as initial values. So, if I understand correctly, I need to compute temperature, given `q_t` and `\theta_l`, in order to convert and solve in terms of internal energy.

I'm happy to use a more direct relation between liquid potential temperature and internal energy if there is one.

**Comment by tapios** [comment]
But the initial condition is unsaturated, right? So you can straightforwardly extract temperature (without iteration) and get internal energy from it.

**Comment by trontrytel** [comment]
We won't be able to hide from it for long. DYCOMS case starts saturated.

**Comment by tapios** [comment]
But DYCOMS starts well mixed in theta_l below inversion and is unsaturated above inversion. So you can get what you need from getting temperature from the unsaturated surface, then, e.g., assuming well mixed MSE to get e_int. No need to add code just for that.

**Comment by charleskawczynski** [comment]
Ok, I think that only some functions are needed-- many functions from the current formulation can be used, but the `theta_l-q_t`-based saturation adjustment is nice to have so that we can get temperature. From there we can get all of the other variables.

**Comment by charleskawczynski** [comment]
Closed by #147
