### ISSUE TITLE
planet parameters

### ISSUE THREAD

**Issue by trontrytel** [climate-machine/CLIMA#136]
In Planet Parameters:
- T_min for saturation adjustment is 150K. Do we really think it should be this low?
- molmass_ratio and eps_vi are the same thing

**Comment by tapios** [comment]
* I removed the eps_v and eps_vi (molmass_ratio is actually being used in MoistThermodynamics, and we should use this consistently throughout)
* 150 K for T_min is low, but not impossibly low. I'd rather have this low so we do not run out of bounds; the lower bound should not matter much in practice. (And we should get away from the saturation adjustment soon anyway.)
