### ISSUE TITLE
AppVeyor team?

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#162]
Currently AppVeyor is under @charleskawczynski personal account. Do we want to create a team for this so that others have admin rights?

**Comment by charleskawczynski** [comment]
Oops! Yes, let's do that.

**Comment by jkozdon** [comment]
Probably best if you or @simonbyrne set this up: https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

**Comment by simonbyrne** [comment]
I've set up a joint one at https://ci.appveyor.com/project/climate-machine/clima (see #163).

@jkozdon you appear to also have a CLIMA build running under your own appveyor account, which appears to be causing confusion (e.g. the Appveyor link now links to https://ci.appveyor.com/project/jkozdon/clima/builds/23750685)

**Comment by jkozdon** [comment]
Killed mine. Sorry this was from when I was messing things earlier.

**Comment by simonbyrne** [comment]
That seems to have fixed it, thanks!

**Comment by simonbyrne** [comment]
Fixed by #163
