### ISSUE TITLE
Writing pvtu file

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#171]
Currently we vtk file for each MPI rank, so we should create a pvtu file to combine these.

Will try to find an example and post it here.

See also https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf

**Comment by smarras79** [comment]
I  believe @asraero has implemented this in his fork. @asraero  can you confirm?

**Comment by jkozdon** [comment]
closed by #229
