### ISSUE TITLE
Remove MPI dependency

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#172]
Basic idea to remove MPI

```julia
abstract type AbstractComm end

# for MPI
struct MPIComm <: AbstractComm
  comm::MPI.Comm
end

# for without MPI
struct SelfComm <: AbstractComm
  # might be needed if we ever want to support multiple communicators on the MPI side.
  comm::Int
end
```

Doing this will require moving [`Canary.jl`](https://github.com/climate-machine/Canary.jl) into CLIMA

See also how [`GPUArrays.jl`](https://github.com/JuliaGPU/GPUArrays.jl) handles the issue.

**Comment by jkozdon** [comment]
With this issue we may want to consider how to do some sort of communicator based extension of the Julia logger.

**Comment by tapios** [comment]
Is this still an issue?

**Comment by jkozdon** [comment]
Yes, in the sense that `MPI.jl` is still required to run the code

**Comment by jkozdon** [comment]
I'm fine closing this if we always want to have a hard dependency on `MPI.jl`
