### ISSUE TITLE
Undefined variable in surface fluxes docs example

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#184]
In the docs example [Nishizawa2018](https://github.com/climate-machine/CLIMA/blob/db2b5bf937aa67cdf6d3d470d718b4d9f34a8919/docs/src/Atmos/SurfaceFluxes.md) of `SurfaceFluxes.md` there is an undefined variable `flux`

**Comment by charleskawczynski** [comment]
Closed by #188
