### ISSUE TITLE
Thermodynamics additions/checks needed

### ISSUE THREAD

**Issue by tapios** [climate-machine/CLIMA#20]
- Thermodynamics.jl should be checked carefully

- Tests should be added. For example, we must have

air_pressure([1, 1], [1, 1], [1, 0], [0, 0]) = [R_v, R_d]
latent_heat_vapor(T_0) = L_v0
latent_heat_fusion(T_0) = L_f0
latent_heat_sublim(T_0) = L_s0
sat_vapor_press_liquid(T_triple) = sat_vapor_press_triple
sat_vapor_press_ice(T_triple) = sat_vapor_press_triple

- As the dycore evolves, we should make sure the data structure for moisture variables (e.g., q_t, q_l, q_i) in the thermodynamics module is consistent with how the thermodynamic functions are called from the dycore and parameterizations. We may need to adapt these.

**Comment by jkozdon** [comment]
addressed by #32
