### ISSUE TITLE
GPU nightly failure

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/CLIMA#232]
See https://gitlab.com/JuliaGPU/CLIMA/-/jobs/214079179

**Comment by jkozdon** [comment]
Maybe we should somehow run on Julia 1.2-backports?

On May 16, 2019, at 5:01 PM, Simon Byrne <notifications@github.com<mailto:notifications@github.com>> wrote:


See https://gitlab.com/JuliaGPU/CLIMA/-/jobs/214079179

**Comment by vchuravy** [comment]
The odd thing is that this seems to be a precompilation issue and not a GPU specific one

**Comment by vchuravy** [comment]
x-ref: https://github.com/JuliaGPU/CUDAnative.jl/issues/407

**Comment by simonbyrne** [comment]
No longer an issue...

**Comment by vchuravy** [comment]
Fixed upstream as well.
