### ISSUE TITLE
rain velocity rho/rho_ground factor

### ISSUE THREAD

**Issue by trontrytel** [climate-machine/CLIMA#275]
Should rain terminal velocity be multiplied by (rho/rho_surface)^(1/2)?

See for example https://doi.org/10.1175/1520-0493(1996)124<0487:TTLSLM>2.0.CO;2

Assigned to me (@trontrytel)

**Comment by tapios** [comment]
I see no physical reason why this would make sense. It's non-causal. Why should a falling raindrop know about the density at the ground before hitting it? It suspect this factor comes from empirical formulae used to fit radar observations.

**Comment by trontrytel** [comment]
I agree. I just want to track the paper with an explanation. So that we can for sure decide not to do it. Its just a reminder that I should check it

**Comment by mwarusz** [comment]
It seems like this factor was introduced by Kessler in https://doi.org/10.1007/978-1-935704-36-2_1 (eq. 7.1 on page 20). His earlier papers don't have it, compare eq. 37 on page 23 in

http://www.atmos.albany.edu/facstaff/rfovell/ATM562/kessler-1967.pdf

I don't see much of an explanation, but I will let @trontrytel  figure it out.

**Comment by trontrytel** [comment]
I think the issue is that they assume a constant coefficient multiplying the square root of drop radius:

v(r) = K sqrt(2r)

But from the force balance when you consider also buoyancy, there should be a  square root(1/air_density) factor there (see terminal velocity in our docs). So thats the argument for adding back the sqrt(1/air density). I have no explanation for air density at the ground. 

Assuming air density at the ground = 1.2kg/m3 we would get the coefficient used in Kessler paper sqrt(2 K rho_ground) = 201. For our formulation it is sqrt(8/3/C_drag (\rho_water - rho_air) g). For C_drag=0.55 we get 218. So I think it's all consistent and we don't need to add it.
