### ISSUE TITLE
example2 : Kessler 

### ISSUE THREAD

**Issue by trontrytel** [climate-machine/CLIMA#276]
The Kessler microphysics example doesn't work when you try to advect rain with rain velocity. Possible suspects are:
 - wrong boundary condition at the top of the domain
 - ripples in the solution for q_rain
 - not enough diffusion to make things stable. 

This should be solved before we try to use this microphysics in LES setups. 

I tag: @trontrytel , @lcw and @smarras79

**Comment by charleskawczynski** [comment]
@trontrytel is this still an issue?
