### ISSUE TITLE
dt update operation unclear

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#296]
It is not clear why it is necessary to use the whole set of calls listed below to update dt at every time step:

```   
 lsrk = LSRK54CarpenterKennedy(spacedisc, Q; dt = dt, t0 = 0)
cbdt = GenericCallbacks.EveryXSimulationSteps(1) do (init=false)
                DGBalanceLawDiscretizations.dof_iteration!(spacedisc.auxstate, spacedisc,
                                                           Q) do R, Q, QV, aux
                                                               @inbounds let
               ... ---> CALCULATE new dt BASED ON Courant
               ...
             end
             end
              ODESolvers.updatedt!(lsrk, dt)
```

rather than the way more intuitive and more simple approach in the pseudocode below 

 ``` 
       dt_new = calculate dt based on Courant
       lsrk = LSRK54CarpenterKennedy(spacedisc, Q; dt = dt_new, t0 = 0)
```

am I missing something?

**Comment by jkozdon** [comment]
You can do that if you want, but creating a new object for the time stepper will allocate new arrays for the storing the stages which could be inefficient.

If you do not want to use a callback, but just want to run on time step you can do that then do the update dt when the time stepper returns control to the user.

You also do not need to nest your callbacks as you've done in the code you posted.

**Comment by smarras79** [comment]
Ok, I will test the two options and evaluate.

**Comment by smarras79** [comment]
> You also do not need to nest your callbacks as you've done in the code you posted.
that was a copy-paste error.

**Comment by lcw** [comment]
If you don't want to use the callbacks I woul suggest something like following:

```julia
lsrk = LSRK54CarpenterKennedy(spacedisc, Q; dt = dt, t0 = 0)
solve!(Q, lsrk; timeend = t1)
dt = ... # calculate dt based on Courant
ODESolvers.updatedt!(lsrk, dt)
solve!(Q, lsrk; timeend = t2)
```

**Comment by smarras79** [comment]
> If you don't want to use the callbacks I would suggest something like following:
> 
> ```julia
> lsrk = LSRK54CarpenterKennedy(spacedisc, Q; dt = dt, t0 = 0)
> solve!(Q, lsrk; timeend = t1)
> dt = ... # calculate dt based on Courant
> ODESolvers.updatedt!(lsrk, dt)
> solve!(Q, lsrk; timeend = t2)
> ```

Awesome. That is the clean solution I love!
thanks

**Comment by jkozdon** [comment]
> Awesome. That is the clean solution I love!

Great.
