### ISSUE TITLE
Add dry thermodynamic state

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#334]
We discussed using the limit of `q_tot = 0` handling the dry cases, but there are advantages to adding a dry thermodynamic state. For example, `saturation_adjustment` never needs to be called for a dry thermodynamic state, and it may help track down bugs for these simpler cases. In addition, dry cases may have a smaller memory footprint which could improve performance.

**Comment by simonbyrne** [comment]
Yes!

**Comment by charleskawczynski** [comment]
Closed by #341
