### ISSUE TITLE
Moving coverage out of Travis

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#343]
Since Travis is timing out, it would be nice to move the coverage to our Azure pipeline. However, Azure does not seem to be supported on [codecov-bash](https://github.com/codecov/codecov-bash#ci-providers), nor on [Coverage.jl](https://github.com/JuliaCI/Coverage.jl/blob/master/src/codecovio.jl#L73-L134), which does not have an Azure case in `add_ci_to_kwargs` and `prepare_request`.

**Comment by simonbyrne** [comment]
I'm looking into it now.

**Comment by charleskawczynski** [comment]
Closed by #342
