### ISSUE TITLE
ETOPO1 topography files from NOAA

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#354]
The topography is currently built as described in PR [329](https://github.com/climate-machine/CLIMA/pull/329). The topography files are taken from the ETOPO1 database by NOAA (1 arc minute global topography) described [here.](https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.ngdc.mgg.dem:316)

To automate the topography handling when a user needs a specific region on the earth, there are two options to be considered: 

OPTION 1:
1.a) Download the global ETOPO1 XYZ topography file from: 
https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO1/data/ice_surface/grid_registered/xyz/ETOPO1_Ice_g_int.xyz.gz

This is a simple text file that contains a list of XYZ points where X and Y are the lat-lon coordinates on a projected plane map and Z is the local topography height.

1.b) read it it into CLIMA (using PR [329](https://github.com/climate-machine/CLIMA/pull/329)) and write a script to extract a specific region given a user's defined domain (lon_min, lon_max, lat_min, lat_max).

OPTION 2 (which I wouldn't recommend):
2.a) Let the user select a region on the NOAA interface and download the data of that region only. The tool provided by NOAA for this purpose is at [this link](https://maps.ngdc.noaa.gov/viewers/wcs-client/)

What I described above should apply to any format available from the ETOPO1 DB. These formats are:
- XYZ (currently in CLIMA)
- netCDF (Version: 4.3.1)
- GRD98
- binary

If needed, I have the C scripts to read the binary format in.

A note on grid resolution and smoothing:
In atmospheric models, it is customary to smooth the topography. As we go to high-order and high resolution, we may not longer want to do it, but it's something to keep in mind.

**Comment by tapios** [comment]
Thanks, @smarras79. My suggestion would be by default to smooth the topography to the effective resolution of the mesh. Do you have anything like that built into your topography setup right now?

**Comment by smarras79** [comment]
Hi @tapios 
The way it is done now is very simple and @asraero found the most efficient solution for that. We are using a 2D interpolation of the topography data onto the grid resolution that we want. That should automatically smooth it out.
