### ISSUE TITLE
Dycoms saturation adjustment changing initial state at 1st time step

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#358]
The current version of dycoms is now initialized as described in section 9.4 of the CLIMA-doc: "_Dynamics and Chemistry of Marine Stratocumulus: DYCOMS RF01_"

however, the first time step (at timeend = dt = 1e-12 s), the filed is adjusted in such a way that the prescribed value of q_liq is drastically changed.

Stevens et al. (2005) make a statement regarding q_liq that makes me think that that's what the issue is for us:

> Modeling groups were also asked to **standardize** their thermodynamic calculations so that the initial state corresponded to a cloud layer between 600 and 800 m with ql =0.45 g/kg at cloud top.'

The initialization is done here:

https://github.com/smarras79/CLIMA/blob/dycoms-sync/test/DGmethods/compressible_Navier_Stokes/dycoms-analyticinit.jl#L714

**Comment by charleskawczynski** [comment]
I'll take a look at this.

**Comment by charleskawczynski** [comment]
From what I gather after speaking with @smarras79 

 - A `PhaseNonEquil` can be used for initialization to achieve a desired `q_liq` profile. However, if `LiquidIcePotTempSHumEquil_no_ρ(θ_liq_ice, q_tot, p)`is subsequently used to establish a thermodynamic state, then saturation adjustment may change `q_liq` dramatically.

 - An additional constructor exists, `LiquidIcePotTempSHumEquil_no_ρ`, where `q_liq` is prescribed (`PhasePartition(LiquidIcePotTempSHumEquil_no_ρ(θ_liq_ice, PhasePartition(q_tot, q_liq, q_ice), p)).liq == q_liq`). However, this means that `q_liq` must be known, and if it's not advanced in time in the state vector, then we need an additional equation.

Ultimately, I think we need to know how `q_liq` is computed in the [stevens paper](https://journals.ametsoc.org/doi/pdf/10.1175/MWR2930.1).

**Comment by smarras79** [comment]
> Ultimately, I think we need to know how `q_liq` is computed in the [stevens paper](https://journals.ametsoc.org/doi/pdf/10.1175/MWR2930.1).

**Comment by smarras79** [comment]
Sorry, closed accidentally after editing a reply.

**Comment by tapios** [comment]
There are a couple things strange (and inaccurate) about the initialization here, e.g., about how temperature is computed from theta_l with linearizations that are not general, and how pressure is computed from that (leading to unphysical kinks in pressure—they imply unphysical accelerations). I’ll write out how to do it tomorrow.
The “standardization” can probably be achieved by slight shifts in q_t.

**Comment by smarras79** [comment]
> There are a couple things strange (and inaccurate) about the initialization here, e.g., about how temperature is computed from theta_l with linearizations that are not general, and how pressure is computed from that (leading to unphysical kinks in pressure—they imply unphysical accelerations). I’ll write out how to do it tomorrow.
> The “standardization” can probably be achieved by slight shifts in q_t.

The initial state has now been modified according to the latest description in the CLIMA-doc that @tapios modified today.

**Comment by smarras79** [comment]
This has been solved by lowering q_tot(t=0) to 8.1 g/kg as suggested by @tapios .
See Full description of this test case in the CLIMA-doc.
