### ISSUE TITLE
Change balance law solver coordinate names

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#366]
Following changes need to be made
- `x` -> `x1`, `y` -> `x2`, `z` -> `x3`
- `ξ` -> `ξ1`, `η` -> `ξ2`, `ζ` -> `ξ3`

vector and tensor components in the Cartesian coordinates `x1, x2, x3` should also be changed:

- `u`->`u1`, `v`->`u2`, `w`->`u3`
- `Fx_x`->`F11`, `Fx_y`->`F12`, etc.

We do not plan to make substantial changes to tests in `test/DGmethods_old` (only enough to get code working)

This allows the computational coordinates to be distinct from the model/physical coordinates (e.g., `z` can be vertical always)

**Comment by jkozdon** [comment]
PR #368 partially addresses this.

The following files should be checked/modified

(Feel free to add to PR #368 if it hasn't been merged yet)

- [ ] `docs/src/VariableList.md`
- [ ] `docs/src/Utilities/MoistThermodynamics.md`
- [ ] `docs/src/Atmos/SurfaceFluxes.md`
- [ ] `docs/src/Atmos/TurbulenceConvection.md`
- [ ] `src/Atmos/Model/moisture.jl`
- [ ] `src/Atmos/Model/radiation.jl`
- [ ] `test/Atmos/Parameterizations/TurbulenceConvection/StateVecFuncs.jl`
- [ ] `src/Atmos/Parameterizations/SurfaceFluxes/SurfaceFluxes.jl`
- [ ] `docs/src/Atmos/EDMFEquations.md`
- [ ] `src/Atmos/Parameterizations/TurbulenceConvection/Grids/Grids.jl`
- [ ] `src/Atmos/Parameterizations/TurbulenceConvection/StateVecs/StateVecFuncs.jl`

cc: @simonbyrne @tapios @asraero @charleskawczynski

**Comment by charleskawczynski** [comment]
I'll PRs to adjust the coordinates for those outside the `TurbulenceConvection/` folder, since that's a stand-alone finite difference implementation of the EDMF equations. Maybe I'll change the folder name to `TurbConvStandAlone`, too.
