### ISSUE TITLE
vtk for new DGmodel

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/CLIMA#370]
Since state variables have names, we should export these to vtk

**Comment by jkozdon** [comment]
We could also use VTK vector types for vector quantities (right now everything is exported as scalar)

**Comment by charleskawczynski** [comment]
I added a function in #388 to collect `BalanceLaw` variable names to pass into `writevtk`. Adjusting it for vector/tensors would be pretty simple since, right now, it appends a linear index for each component.

**Comment by charleskawczynski** [comment]
Should we close this?
