### ISSUE TITLE
should `init_state!` use `LocalGeometry`?

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#416]
Wondering if the way that coordinates are handled for [`init_state!`](https://github.com/climate-machine/CLIMA/blob/27c178d4e5cda87215f9afe3c98e80953c375b51/src/DGmethods/DGmodel_kernels.jl#L574) should match the way that they are handled for [`init_aux!`](https://github.com/climate-machine/CLIMA/blob/27c178d4e5cda87215f9afe3c98e80953c375b51/src/DGmethods/DGmodel_kernels.jl#L607). Namely, should the `LocalGeometry` type be used instead of just an `Tuple`?

**Comment by simonbyrne** [comment]
On that note: is there any reason we couldn't pass `LocalGeometry` to all functions?

**Comment by jkozdon** [comment]
You just mean as opposed to shoving things in `aux`? I guess the concern would be loading stuff in performance parts of the code that are not needed. But if we can figure out how to prevent this (or if unneeded loads are being optimized away) this would be fine.
