### ISSUE TITLE
Assess incompressibility as a diagnostic criterion

### ISSUE THREAD

**Issue by blallen** [climate-machine/CLIMA#477]
as a sanity check for the Ocean model, we would like to have `∇·u` computed and stored as a function of space and time. For now, I'm trying to do this through auxiliary variables, I'm sure we'll eventually have a better interface. 

Currently, `update_aux!` / `nodal_update_aux!` only know about state and auxiliary variables. However, we need the derivatives of state variables to compute the divergence-free criteria. Does it make sense to just add the diffusive terms as arguments to these functions? Do these arrays maintain their values between time steps?

Furthermore, for the hydrostatic ocean model, we need `∂w/∂z` in order to compute the full 3D divergence. Is there an easy way to get derivatives/gradients of auxiliary variables? Seeing as we compute `w` as integral, we probably already have this information [1] , but I'm not sure what exactly corresponds to `∂w/∂z`.

Does anyone have some ideas here?

@jkozdon @lcw @simonbyrne @charleskawczynski @sandreza @christophernhill

[1] https://github.com/climate-machine/CLIMA/blob/jek/ocean3d/src/Ocean/Model/OceanModel3D.jl#L206-L234

**Comment by lcw** [comment]
Brandon Allen <notifications@github.com> writes:

> Currently, `update_aux!` / `nodal_update_aux!` only know about state
> and auxiliary variables. However, we need the derivatives of state
> variables to compute the divergence-free criteria. Does it make sense
> to just add the diffusive terms as arguments to these functions? Do
> these arrays maintain their values between time steps?

That seems reasonable to me.  Right now I believe the diffusive
arrays maintain their values between steps.

> Furthermore, for the hydrostatic ocean model, we need `∂w/∂z` in order
> to compute the full 3D divergence. Is there an easy way to get
> derivatives/gradients of auxiliary variables? Seeing as we compute `w`
> as integral, we probably already have this information [1] , but I'm
> not sure what exactly corresponds to `∂w/∂z`.

You probably want to compute the 3D DG divergence right? For that you
need to create a DGModel for this computation.

**Comment by blallen** [comment]
> That seems reasonable to me. Right now I believe the diffusive arrays maintain their values between steps.

Okay, so I can at least get the 2D DG divergence using this. It will just have the values from the previous time step (where both volume and face contributions were calculated).

> You probably want to compute the 3D DG divergence right? For that you need to create a DGModel for this computation.

If I have the 2D DG divergence from the diffusive variables, I would only need a DGmodel for `∂w/∂z`, right? But that seems like overkill for wanting to take a derivative only as a diagnostic variable and not as a prognostic variable. 

@sandreza and I have been thinking about implementing a DG derivative/gradient operator that exists independently of the tendency/rhs calculation. This seems like it might be a good test case for developing that idea

**Comment by charleskawczynski** [comment]
> Currently, `update_aux!` / `nodal_update_aux!` only know about state and auxiliary variables.

This is something I've brought up several times with @asraero, I suspect that this need will show up often. It seems to make sense to have something like

```
update_aux!
compute_gradients!
update_aux_gradients_aware!
flux!
sources!
```

Or something like this. This way, we can build relatively complex kernels that include gradients, when needed for fluxes/sources.

**Comment by blallen** [comment]
(We should also move integral computation outside of `update_aux!` and make a dedicated class of integral variables, basically adding `compute_integrals!` and `update_aux_integrals_aware!`, so we should try to think of a way to handle this that allows for an arbitrary amount of classes of non-state fields
