### ISSUE TITLE
DG tests that need to be moved to the new framework

### ISSUE THREAD

**Issue by mwarusz** [climate-machine/CLIMA#491]
I discussed with @lcw and @jkozdon which DG methods tests/examples need to be moved to the new framework so that we can finally kill the old one. I marked those that have been moved but not yet merged. 

- [ ] test/DGmethods_old/conservation/sphere.jl
- [x] test/LinearSolvers/poisson.jl
- [x] test/DGmethods_old/util/filter_test.jl
- [x] test/DGmethods_old/util/nonnegative_test.jl
- [x] test/DGmethods_old/sphere/advection_sphere_*
- [ ] examples/DGmethods_old/ex_004_nonnegative.jl

The last two can be combined into one test and I will try to do that this week.

Additionally, the following could be moved but there is no functionality to take local gradient of auxiliary state in the new framework.
- ~~test/DGmethods_old/util/grad_test.jl~~ (not grad aux in new framework)
- ~~test/DGmethods_old/util/grad_test_sphere.jl~~  (not grad aux in new framework)

@simonbyrne

**Comment by trontrytel** [comment]
I'm working on 

- [ ] examples/Microphysics/ex_1_saturation_adjustment.jl
- [ ] examples/Microphysics/ex_2_Kessler.jl

**Comment by jkozdon** [comment]
Should this be part of [milestone 1](https://github.com/climate-machine/CLIMA/milestone/1)?

**Comment by charleskawczynski** [comment]
We're so close that, it seems, it would be a shame if we couldn't include it. Does @mwarusz have any bandwidth to tackle the last example? (that is the last one, right?)

**Comment by charleskawczynski** [comment]
Also, if we do close this issue out, we'd be able to remove `CLIMA/src/DGmethods_old`, correct?

**Comment by jkozdon** [comment]
> We're so close that, it seems, it would be a shame if we couldn't include it. Does @mwarusz have any bandwidth to tackle the last example? (that is the last one, right?)

I can do try to do it in the next week or two if @mwarusz doesn't get to it.

> Also, if we do close this issue out, we'd be able to remove `CLIMA/src/DGmethods_old`, correct?

Yes we can remove `DGmethods_old`.

**Comment by mwarusz** [comment]
"Also, if we do close this issue out, we'd be able to remove CLIMA/src/DGmethods_old, correct?"

Yes.

Apparently `test/DGmethods_old/conservation/sphere.jl` was moved to the new framework but never got merged (it is on the branch `sb/new-dg-test`). So there is one test that needs to be updated and one example that needs to be moved.

I could do that next week.
