### ISSUE TITLE
Checkpointing/restart

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#50]
We need a way to checkpoint the Dycore for restarts (likely requires wrapping MPI I/O stuff).

**Comment by simonbyrne** [comment]
From discussion today:

We need:

Interface

- Specify checkpoint interval 
`--checkpoint-wallclock` / `--checkpoint-simtime`

-Option to checkpoint at end
`--checkpoint-atend`
`--checkpoint-remove-old` to keep only the most recent checkpoint

Format
- 1 file per checkpoint per rank
- if we have parallel I/O we can do 1 file per checkpoint
    -would need to precompute offsets
- NetCDF for now
- checkpoint state / aux / t
   - figure out how to handle multistate
- checkpoint grid at start vgeo/sgeo 
   - probably not now, only if necessary

Restart
- `--restart=filename` ?
  - Does the user provide the filename, or do we autodetect?
- For the time being, we assume `--nprocs`/topology is the same
   - To support different number of ranks we will need a mechanism to reorder topology layout

**Comment by simonbyrne** [comment]
@leios will look into parallel netcdf

**Comment by christophernhill** [comment]
@leios do you want to chat briefly about “zarr” -
https://www.unidata.ucar.edu/blogs/news/entry/netcdf-and-native-cloud-storage
sometime this week?

 Oliver has been tinkering with zarr over the last month. He seems
relatively pleased with it. He has high standards and good judgement, so it
might be worth a quick chat?

Thanks,

Chris

**Comment by akshaysridhar** [comment]
#576 provides a start based on existing `DGmodel.jl` functionality.
