### ISSUE TITLE
Support for higher order DG on GPU

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/CLIMA#502]
@lcw could you link to the upstream issues?

**Comment by lcw** [comment]
The high-order volume kernels are currently slower than the CUDA-C version compiled by LLVM. See
https://github.com/JuliaGPU/CUDAnative.jl/issues/398.

**Comment by blallen** [comment]
@lcw @mwarusz 

how do we implement the fix in CLIMA.jl ? Do we just need to make CLIMA set `JULIA_LLVM_ARGS="-instcombine-code-sinking=false"` by default?

**Comment by lcw** [comment]
No. Someone needs to implement the stacked kernels in CLIMA.  The means
adapting
https://github.com/lcw/Heptapus.jl/blob/d7dfa1debbf4ec564321b29a87c17eb304c00c46/examples/volumerhs-small/volumerhs.jl#L75-L224
for the CLIMA volume kernels.

**Comment by leios** [comment]
I wouldn't mind looking into this. @mwarusz is currently translating everything into kernel abstractions, so now is roughly a good time to think about it.
