### ISSUE TITLE
1D GMRES

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#513]
This has been brought up on slack, but figured an issue would be good so all are aware of the issues.

I was mistaken in PR #499 for the behavior of 1D IMEX with GMRES. Currently the GMRES solver with block diagonal systems does not actually do GMRES on each column but instead does global GMRES with a single norm and upper Hessenberg matrix.

To extend the GMRES solver to per-column behavior we need to:

- add a column-wise norm
- have a unique upper Hessenberg matrix for each column
- (optionally) mask out columns which have already converged

**Comment by simonbyrne** [comment]
On the last point: is there a danger if we do keep iterating GMRES after it has converged? Is there a risk it might start to diverge?

**Comment by jkozdon** [comment]
Its possible to get `NaNs` with some iterative solvers, not sure about GMRES
