### ISSUE TITLE
`CuArrays` not part of dependencies

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#516]
```
 ┌ Warning: Package CLIMA does not have CuArrays in its dependencies:
│ - If you have CLIMA checked out for development and have
│   added CuArrays as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with CLIMA
└ Loading CuArrays into CLIMA from project dependency, future warnings for CLIMA are suppressed.
```

Not sure where the problem is coming from, but something we likely want to fix:
https://gist.github.com/climabot/57e451e3b3dd8669e6e56051dfb6d627#file-out_7701599-L53-L70

**Comment by simonbyrne** [comment]
There were recently some updates to the CUDA stack that should allow us to utilize one Project.toml file. I'll try to update #493 to use this.

**Comment by charleskawczynski** [comment]
Can we close this?
