### ISSUE TITLE
git-ocalypse!

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#542]
Just a last minute reminder! Per slack:

 > So what we are going to do is a sort of “git-ocalypse”: this weekend I am going to rewrite all the branches on the main CLIMA repository. What you will need to do:
 - Before Friday, push any personal branches you have to the main CLIMA repository (NOT your personal fork).
    - A useful convention is to prefix any personal branches with your initials and a `/` (i.e. mine are named `sb/something`) so it is obvious who it belongs to, and reduces the chances of naming conflicts
 - On Monday, create a fresh clone of the CLIMA repository

**Comment by simonbyrne** [comment]
Completed!
