### ISSUE TITLE
Diagonalize functions that act on primitive types

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#55]
I think that it would be wise to diagonalize types in functions that act on primitive types (e.g., MoistThermodynamics.jl), to provide some protection against mixed types getting accidentally passed in. For example, 

Convert the following function signature from
```
function internal_energy_sat(T, ρ, q_t)
...
end
```
to
```
function internal_energy_sat(T :: R, ρ :: R, q_t :: R) where R <: Real
...
end
```

**Comment by tapios** [comment]
Sounds good to me. Would you mind doing it?

**Comment by charleskawczynski** [comment]
Yes, I can do this. @lcw , @jkozdon , are there any issues with diagonalizing types like this for GPU usage? Or is an okay move?

**Comment by lcw** [comment]
It should work okay on the GPU.  Would there ever be a situation where we might want to run with different precisions (for example half and single on the TPU)?

**Comment by charleskawczynski** [comment]
That's a great question. I'm not really sure how these methods will work with TPUs. Maybe the safe bet is to keep the interfaces flexible for now. I've gotten the impression that GPUs like flexible types while working on the GPU tests for #56.

Also, some of the moist thermo methods may need to be reworked due to lack of GPU support for complex closures. I'll work on this once #56 is resolved.

**Comment by tapios** [comment]
It would be good to build-in an ability to run with reduced precision--we may need it in the future.

**Comment by charleskawczynski** [comment]
I think the consensus is that we’ll develop using generic types in case we want to use mixed precision. So I’ll close this.
