### ISSUE TITLE
Multirate Solver will fail if time end value is integer and not converted to Float

### ISSUE THREAD

**Issue by slifer50** [climate-machine/CLIMA#579]
As title states the MultirateRungeKutta kept failing with method not matched error. This was resolved by converting timeend to a float. If possible it might be best to not have this issue, especially since the error message does not indicate this. @simonbyrne

**Comment by charleskawczynski** [comment]
Can you share the stacktrace?

**Comment by kpamnany** [comment]
I don't think this is really an issue. The `timeend` parameter in [`solve!`](https://github.com/climate-machine/CLIMA/blob/master/src/ODESolvers/ODESolvers.jl#L56) is `Real`.
