### ISSUE TITLE
Reference state in HS state

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#591]
Why is there this check? Isn't the reference state always supposed to be in HS state?

https://github.com/climate-machine/CLIMA/blob/a1bc4b2e459bdb69a2c228feeffae4d64ec25b30/src/Atmos/Model/AtmosModel.jl#L136

**Comment by simonbyrne** [comment]
It is possible to run it without a reference state. Should we require a reference state?

**Comment by fxgiraldo** [comment]
We need a reference state for the linear IMEX solvers.  Once we move to nonlinear IMEX solvers, we shouldn't need them.

**Comment by simonbyrne** [comment]
Yes, if you attempt to use IMEX without a reference it will throw an error.

**Comment by tapios** [comment]
> It is possible to run it without a reference state. Should we require a reference state?

We should not always require a reference state, although in practice we may (almost) always use it, for numerical stability reasons alone (factoring it out of the momentum equation). But it's good to keep the option to run standard flow models without gravity and without hydrostatic balance.

I see no harm in explicitly enforcing hydrostaticity in l. 136, even if right now reference states are hydrostatic (and most of the time will be, except perhaps in some flows without gravity).

**Comment by tapios** [comment]
Is this issue still open or can it be closed?

**Comment by smarras79** [comment]
> Is this issue still open or can it be closed?

It's related to [](url)

**Comment by smarras79** [comment]
(closed accidentally)
