### ISSUE TITLE
Unable to weak scale

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/CLIMA#595]
Testing with @smarras79's [branch ](https://github.com/climate-machine/CLIMA/tree/sm/yt-DYCOMS-MULTI-RATE-NEW-MOIST-THERMO) using a resolution of 40x10, GPU memory is exhausted for a 5000x5000x2500 grid. But increasing the number of ranks has no effect on the maximum grid dimensions.

Will work with @lcw and @jkozdon to resolve.

Cc: @simonbyrne.

**Comment by lcw** [comment]
I am happy to help but I need more information.  It would also be useful if the problem can me realized with one of the examples in the master branch.

**Comment by kpamnany** [comment]
Found the problem with @lcw's help -- not using `device!` in the old driver. This is resolved in https://github.com/climate-machine/CLIMA/pull/597 which should subsume all previous DYCOMS drivers when merged.

**Comment by smarras79** [comment]
> Found the problem with @lcw's help -- not using `device!` in the old driver. This is resolved in #597 which should subsume all previous DYCOMS drivers when merged.

Amazing! thanks @kpamnany and @lcw

**Comment by fxgiraldo** [comment]
Great news!
