### ISSUE TITLE
diffusive! should be linear in ∇transform

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/CLIMA#605]
After some discussion with @fxgiraldo, it seems that for the `diffusive_penalty!` to be applied correctly, we require that `diffusive!` be a linear function of `∇transform`. Any other operations should be moved into `flux_diffusive!`.

**Comment by blallen** [comment]
Is there any reason the linear transforms couldn't also be done in `flux_diffusive!`? When we were at NPS, @jkozdon and @lcw said the main purpose of `diffusive!` was to implement the non-linear transforms. 

While performing the diffusive transform does reduce the dimensionality of the inputs to the diffusive flux, it also introduces an additional layer of complexity to the code as you have to define `gradient_variables` and `diffusive_variables` separately. If we perform all the manipulations of the gradients within `flux_diffusive!`, we only need to define one set of `gradient_variables` to be used everywhere. This also results in a closer corresponds to the sets of variables used in the DG literature.

**Comment by simonbyrne** [comment]
To (partially) clarify what the issue is: 
1. `gradvariables!` (G in the design docs) computes `transform` 
2. the DG kernels compute its gradient `∇transform`
3. `diffusive!` (D in the design docs) takes `∇transform` and returns a reduced quantity (called `diff`) 
4. `flux_diffusive!` takes `diff`

At the boundary, `diffusive_penalty!` also calls `diffusive!` but instead of `∇transform` it passes in `n_Δdiff = n * (transform⁺ - transform⁻)/2`:
https://github.com/climate-machine/CLIMA/blob/c6421dcce79a88959037bc48d32426a41829b208/src/DGmethods/NumericalFluxes.jl#L43-L51
This doesn't seem right: for one thing, it has the wrong units: e.g. if `n_Δdiff` will have the same units as `transform`, whereas `∇transform` it is divided by the spatial unit.

From some discussion with @fxgiraldo, my understanding is that this term arises by application of the product rule, which would require that `diffusive!` be linear in `∇transform`. That said, it would be good to clarify this derivation in the design docs.

**Comment by lcw** [comment]
> Is there any reason the linear transforms couldn't also be done in `flux_diffusive!`? When we were at NPS, @jkozdon and @lcw said the main purpose of `diffusive!` was to implement the non-linear transforms.

From what I remember, `diffusive!` was designed to reduce the storage of the gradient.  For example, store the stress instead of the strain (6 variables instead of 9).

**Comment by jkozdon** [comment]
> This doesn't seem right: for one thing, it has the wrong units: `n_Δdiff` will have the same units as `transform`, whereas in `∇transform` it is divided by the spatial unit.

The units get fixed by the fact that `n_Δdiff` is involved in a surface integral whereas `∇transform` a volume integral.

> From some discussion with @fxgiraldo, my understanding is that this term arises by application of the product rule, which would require that `diffusive!` be linear in `∇transform`. That said, it would be good to clarify this derivation in the design docs.

You can motivate DG via integration by parts type arguments, but really we just propose a weak form and (try) to show that it is consistent and stable.

I agree though, the we are on the most solid footing if we can keep the diffusive terms linear and just have nonlinearity in the `gradvariables!`.

**Comment by simonbyrne** [comment]
> From what I remember, `diffusive!` was designed to reduce the storage of the gradient. For example, store the stress instead of the strain (6 variables instead of 9).

That was what I assumed.

> The units get fixed by the fact that `n_Δdiff` is involved in a surface integral whereas `∇transform` a volume integral.

Yes, but we require that `diffusive!` be valid for both interpretations: a sufficient condition is that `diffusive!` is linear.

**Comment by jkozdon** [comment]
> Yes, but we require that `diffusive!` be valid for both interpretations: a sufficient condition is that `diffusive!` is linear.

Agreed. Linear make sure you do not muck the units up.
