### ISSUE TITLE
Subsidence not doing what it should. Turn off while 

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#634]
While refactoring, please 

1. replace `D_subsidence  = FT(3.75e-6)` with `D_subsidence  = FT(0)` to preserve the code stable all the way to completion.

2. replace `C_smag = FT(0.18)` with `C_smag = FT(0.21)`

This changes are only meant to make the driver robust for the whole 4hrs of simulated time.

https://github.com/climate-machine/CLIMA/blob/f0e04e5cd2f52f554ba536d4070020a0e130b547/test/DGmethods/compressible_Navier_Stokes/ex_001_dycoms-imex.jl#L204

**Comment by kpamnany** [comment]
These parameters are set as you ask above in `experiments/LES/dycoms.jl` so I'll close this in in https://github.com/climate-machine/CLIMA/pull/664 unless you want to expand this issue to explain the problem you're seeing with subsidence?

**Comment by smarras79** [comment]
> These parameters are set as you ask above in `experiments/LES/dycoms.jl` so I'll close this in in #664 unless you want to expand this issue to explain the problem you're seeing with subsidence?

@kpamnany  you can go ahead and close this. I will need to re-test the (potential) issue with subsidence in the current version of the code and this issue may become obsolete.
