### ISSUE TITLE
CLIMA.init breaks Jupyter notebook

### ISSUE THREAD

**Issue by simonbyrne** [climate-machine/CLIMA#655]
Calling `CLIMA.init()` in a Jupyter notebook causes a kernel error. This seems to be due to changes in #597.

**Comment by kpamnany** [comment]
The kernel error arose from `ArgParse.jl` exiting if arguments aren't recognized and the fact that Jupyter also uses a command line argument. Until `ArgParse.jl` supports partial parsing, I've fixed this by ignoring all command line arguments if there are any unrecognized ones iff `isinteractive()`.

**Comment by kpamnany** [comment]
I've tested this locally in a Jupyter notebook, but can you verify also that `kp/fix-init` does fix this?

**Comment by simonbyrne** [comment]
Yep, that works!
