### ISSUE TITLE
Make slurm CI and CLIMA interaction more transparent

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#675]
This reveals that our CI has a hidden dependency on https://github.com/climate-machine/slurmci not sure if we want to make this more explicit some how (@simonbyrne, @kpamnany)

_Originally posted by @jkozdon in https://github.com/climate-machine/CLIMA/pull/657#issuecomment-581582239_

**Comment by jkozdon** [comment]
Follow on from @simonbyrne 

I think we should consider moving the slurm scripts back into this repo, as it will make them easier to change.

cc @kpamnany

_Originally posted by @simonbyrne in https://github.com/climate-machine/CLIMA/pull/657#issuecomment-581588053_

**Comment by jkozdon** [comment]
Follow on from @kpamnany 

My thinking was/is that SlurmCI is very specific to the Central cluster and unnecessary for anyone who wants to clone and run CLIMA, or even to contribute. Also, there's a good bit of work still to do in building out the performance analysis and it'll be easier to do there, without needing to open PRs to the main repo.

IMO, we should be moving towards splitting the main repo into more parts rather than the opposite!

_Originally posted by @kpamnany in https://github.com/climate-machine/CLIMA/pull/657#issuecomment-581602665_

**Comment by jkozdon** [comment]
Perhaps to can disconnect the Julia version updates in Slurm and CLIMA through the `slurm-test.toml`? Similar to [`azure-pipelines.toml`]

[`azure-pipelines.toml`]: https://github.com/climate-machine/CLIMA/blob/1c7fa3e05c638cf652226cdd5ff69f8be0969dab/azure-pipelines.yml#L17-L22

**Comment by kpamnany** [comment]
I was just about to post that most of Azure CI's configuration is about Julia versions. We can quite easily add a `julia_version` key in [slurmci-test.toml](https://github.com/climate-machine/CLIMA/blob/master/slurmci-test.toml) and use that in SlurmCI to choose the Julia version to run the tests.

So that will address your concern?

**Comment by kpamnany** [comment]
Though, one could argue that MPI implementation and version also have an important effect. And then it starts getting OTT a bit.

**Comment by jkozdon** [comment]
> Though, one could argue that MPI implementation and version also have an important effect. And then it starts getting OTT a bit.

Outside of collective operations, MPI should not impact the floating point result. Our code should be floating point reproducible (except for collective operations) across MPI partitioning.

**Comment by jkozdon** [comment]
> Come to think of it, it's a bit surprising that Julia isn't floating point reproducible, across 1.2 and 1.3

Agreed that this seems odd... It's on the Float32 results that we are having problems with. Not sure if we would see the same issues on the CPU or just on the GPU (we never run the tests that are failing at the same level of resolution on the CPU).

**Comment by simonbyrne** [comment]
> That's reasonable. Come to think of it, it's a bit surprising that Julia isn't floating point reproducible, across 1.2 and 1.3. Any insight into why this is @simonbyrne ?

Tough to say: could be different BLAS versions doing different vectorization or threading, or different compiler optimizations doing different things wherever `@simd` is used (e.g. inside `sum`), or different use of FMA's in `muladd` (which are used for polynomial evaluations inside transcendental functions).

Julia itself doesn't make any claim on floating point reproducibility, and I would argue it is basically impossible, at least without disabling a whole lot of optimizations.

**Comment by jkozdon** [comment]
opening issue on slurmci; see https://github.com/climate-machine/slurmci/issues/19
