### ISSUE TITLE
Add units to docs in moist-thermo

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#679]
Many functions in moist thermo don't specify the units of input variables, we should specify them.

Some of this may be coming in with #600

**Comment by tapios** [comment]
We are currently using SI units by default. We can spell out what they are in the docs. But an advantage of leaving these unspecified is that it would make it easy to nondimensionalize the code, simply by rescaling thermodynamics (and other) constants in the `PlanetParameters`. That will change the units of inputs and outputs (they become nondimensional), without changing anything else. 

Compromise: List what the units are in SI but make it clear that SI is not a requirement, as long as a consistent system is used?

**Comment by charleskawczynski** [comment]
Good point. This seems like something that pertains across modules, so I'm fine closing this issue. We can declare units in a single place in the documentation.
