### ISSUE TITLE
Required output fields

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#682]
The initial field should be written out to VTK to make sure that fields are initialized correctly. 

This should not only contain the state vector (rho, mome, ene_tot), but also potential temperature, among other derived quantities of interest to users from the atmospheric sciences.

The same quantities should be available at all time steps.

**Comment by kpamnany** [comment]
From my reading of [this](https://github.com/climate-machine/CLIMA/blob/master/src/Driver/Driver.jl#L317-L339) code, it looks like the initial state will be written out to the `step0` file. Is this not working correctly?

**Comment by akshaysridhar** [comment]
Is this still an issue ?
e.g. running the dry-rayleigh-benard problem for 2 timesteps with -> 
`julia --project examples/Atmos/dry_rayleigh_benard.jl` --enable-vtk --vtk-interval=1 --disable-diagnostics` produces a `*step0000.vtu` which shows the initial conditions (in this problem the interesting part is the temperature field)
