### ISSUE TITLE
Convert microphysics examples to new framework

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#683]
Since the Kessler microphysics is [complaining with new versions of CUDA](https://github.com/climate-machine/CLIMA/pull/646#issuecomment-582171483), we should update this example to use the new framework in hopes that this fixes the incompatibility.

**Comment by trontrytel** [comment]
Use pull #781 to zero out pressure and sources coefficients to get a kinematic Atmos Model

**Comment by charleskawczynski** [comment]
Closed by #856
