### ISSUE TITLE
Vertical interpolation along each column

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#69]
The reading of external sounding relies on a 1D column-like interpolation between the sounding levels and the DG grid. This is done using Charlie's function "function get_z_coordinate(mesh::T) where T".

The current implementation of this can only work for flat domains. To work with topography, it will need to be generalized by extracting a one-dimensional DG grid for every column. Because it is possible that the grid structure will change once topography is added, we leave this for later.

**Comment by jkozdon** [comment]
This is dependent on #48

**Comment by lcw** [comment]
Hi @smarras79,

Is this still an issue?

**Comment by jkozdon** [comment]
Can we close this @smarras79
