### ISSUE TITLE
Failure of Rootsolvers test on systems with GPUs

### ISSUE THREAD

**Issue by leios** [climate-machine/CLIMA#698]
Hello, while setting up the system for MIT-ocean folks and updating CLIMA to CuArrays 1.7.0, I noticed a few tests that seem to fail only on systems with a GPU (tested on 3 such systems with varying hardware). I have been working to fix one on `test/Utilities/RootSolvers/runtests.jl`, which had a few errors. The first was that `cu` was not defined. This could be solved by either `using CuArrays` or changing all `cu` calls to `CuArray` in the test file. This is a relatively quick fix.

The more difficult error to solve is the following:
```
RootSolvers CUDA - verbose solution : Error During Test at /home/jars/projects/CLIMA/test/Utilities/RootSolvers/runtests.jl:89
  Got exception outside of a @test
  CuArray only supports bits types
```
The stacktrace took some time to figure out for me, but it comes from this line in the runtest:

```
sol = RootSolvers.find_zero.(f, X0, X1, SecantMethod(), VerboseSolution())
```

Where `X0` and `X1` are CuArrays. This will return an array of VerboseSolutions; however, the `err_history` and `root_history` are both vectors, which causes the error in the VerboseSolution, but not the CompactSolution on GPUs.

I played around a bit with StaticArrays to see if we could circumvent this and still keep the histories, but it does not seem to work. I am more or less documenting this with this issue and will come back to it later. If anyone has ideas on how to fix this, please let me know!

**Comment by charleskawczynski** [comment]
Yes, this got a bit lost in translation. We can actually remove the GPU test here. The `VerboseSolution` is only needed for offline analysis/optimization, which we can do on the CPU.
