### ISSUE TITLE
GCM runs : interactions between Diagnostics.jl and moisture models (undefined var \rhoq_tot)

### ISSUE THREAD

**Issue by akshaysridhar** [climate-machine/CLIMA#699]
Command to replicate this:

`julia --project experiments/GCM/heldsuarez.jl --diagnostics-interval=1` 

Stacktrace : https://gist.github.com/akshaysridhar/791064451d3c9bd008397a7e97cdafef

There is an issue with the way `MoistureModel`, `Diagnostics` interact (and presumably with other such variables defined in `AtmosModel` subcomponents). 

Here, if a `DryModel()` is the moisture model type, there is an issue with getting averages for the moisture variables - a `CLIMA.VariableTemplates.GetVarError` is triggered for the \rhoq_tot variable(e.g. \rhoq_tot which appears in `compute_horzsums!` and `gather_diagnostics`). With `DryModel()` active `state.moisture.\rhoq_tot` is not defined. Interaction with `EquilMoist()` is fine (since we define `state.moisture.\rhoq_tot`)

See also #702 

@slifer50 @kpamnany @bischtob

**Comment by kpamnany** [comment]
Presumably also applies to `diffusive_flx.moisture.∇q_tot`.
