### ISSUE TITLE
Encapsulate the Dycore mesh

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#70]
Right now, it seems that the dycore mesh consists of many tuples of arrays that define relations between element neighbors, vertices etc.

I think it would be good to make a struct `Mesh` and make these mesh-related arrays properties of `Mesh` so that functions calls can have simpler interfaces. For example, in [L2errornorm](https://github.com/climate-machine/CLIMA/blob/master/src/CLIMA-atmos/Dycore/src/VanillaEuler.jl#L587)

`L2errornorm(::Val{dim}, ::Val{N}, time, Q, vgeo, elems, Qexact)`

would become

`L2errornorm(::Val{dim}, ::Val{N}, time, Q, mesh::Mesh, Qexact)`

This will also greatly simplify the mesh initialization, which should be something of the form:

`mesh = Mesh(params)`

**Comment by jkozdon** [comment]
We've been working on this if you look at my branches.
