### ISSUE TITLE
Update subsidence specification 

### ISSUE THREAD

**Issue by tapios** [climate-machine/CLIMA#700]
The way subsidence is specified needs to be modified. We need subsidence to give  a source in the specific humidity and energy equations, i.e.,
`source.e = \rho w_sub k \cdot \nabla h_tot`
where `h_tot` is total enthalpy and 
`source.q_t = \rho w_sub k \cdot \nabla q_t`
where `k` is the vertical unit vector and `w_sub` is a prescribed subsidence velocity (defined positive downward).

This needs to replace the current flux modification.

**Comment by simonbyrne** [comment]
The pragmatic issue is that we can't currently use gradients in the source terms, so we computed it in the flux, since
k̂ ⋅(∇ϕ) = ∇⋅(k̂ ϕ)

@jkozdon mentioned in https://github.com/climate-machine/CLIMA/issues/704#issuecomment-585443977 that there are potential numerical issues with putting stiff terms in the source

**Comment by simonbyrne** [comment]
There is perhaps an argument that we could define a special mechanism for vertical only fluxes.

**Comment by tapios** [comment]
> The pragmatic issue is that we can't currently use gradients in the source terms, so we computed it in the flux, since
> k̂ ⋅(∇ϕ) = ∇⋅(k̂ ϕ)
> 
> @jkozdon mentioned in [#704 (comment)](https://github.com/climate-machine/CLIMA/issues/704#issuecomment-585443977) that there are potential numerical issues with putting stiff terms in the source

Two points (which may be obsolete by now):
1. There are no numerical issues with the source we need here (no stiffness etc.)
2. If you have to use a flux (not my preference because it will not generally work), you can use wk̂⋅ ∇ϕ = ∇(wk̂ ϕ) - ϕ∇(wk̂). This is easy in DYCOMS because ∇(wk̂) = -D = const (but this is not true in all cases where we'd want to use gradients in sources).

**Comment by simonbyrne** [comment]
Ah, right, the coefficients are non-constant.

**Comment by simonbyrne** [comment]
So two potential approaches
1. Use `update_aux_diffusive!` to store the gradient in the `aux`
2. Rearrange the code in the kernels so that `source!` has access to `diffusive` variables.

Not sure which will be easier.

**Comment by charleskawczynski** [comment]
I started to (try to) implement approach 2 in #701, e.g., [here](https://github.com/climate-machine/CLIMA/pull/701/files#diff-fdd3727a0687c5fad0d40e9d53cbd56eR130-R141). I imagine @lcw and @jkozdon would agree to avoid storing more things in `aux`.
