### ISSUE TITLE
Segfault in RootSolvers

### ISSUE THREAD

**Issue by bischtob** [climate-machine/CLIMA#707]
After cloning CLIMA/master and precompiling, some tests run, but not others.
<img width="841" alt="Screen Shot 2020-02-13 at 2 08 20 PM" src="https://user-images.githubusercontent.com/12664448/74483094-95814b80-4e6a-11ea-96b0-d4fa7c786140.png">

**Comment by charleskawczynski** [comment]
#705 should fix this

**Comment by bischtob** [comment]
Same as #709
