### ISSUE TITLE
Use parametric types instead of `using CurrentPrecision: DFloat`

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#71]
Need to convert more of the `DFloat` types to generic types.

**Comment by jkozdon** [comment]
What do you mean?

**Comment by charleskawczynski** [comment]
I mean parametric types, I'll fix the title. Right now I have `using CurrentPrecision: DFloat` in many modules.

**Comment by jkozdon** [comment]
Ah makes sense. Thanks for clarifying.

**Comment by charleskawczynski** [comment]
Closing this since none of this is _in_ master and I'm filtering through everything that I'm folding into master.
