### ISSUE TITLE
Float32 breaks Held-Suarez experiment

### ISSUE THREAD

**Issue by bischtob** [climate-machine/CLIMA#713]
Turns out I ran into issues when running our default Held-Suarez experiment with Float32 instead of Float64 :(...

**Comment by bischtob** [comment]
<img width="1667" alt="Screen Shot 2020-02-14 at 9 52 15 AM" src="https://user-images.githubusercontent.com/12664448/74555044-bb146080-4f0f-11ea-8fc5-60ec97087eea.png">

**Comment by bischtob** [comment]
Apologies for the screenshot. I am having issues with TMUX copy and paste :)...

**Comment by kpamnany** [comment]
Is [this](https://github.com/climate-machine/CLIMA/blob/master/experiments/Atmos_GCM/heldsuarez.jl#L103) the only line you changed?

**Comment by bischtob** [comment]
yes

**Comment by bischtob** [comment]
> Is [this](https://github.com/climate-machine/CLIMA/blob/master/experiments/Atmos_GCM/heldsuarez.jl#L103) the only line you changed?

Yes
