### ISSUE TITLE
FT is cumbersome when setting up experiment files

### ISSUE THREAD

**Issue by bischtob** [climate-machine/CLIMA#736]
It is cumbersome to have to keep track of a floating type method in multiple locations. Would be better to have one location and only one way of switching floating types everywhere in a model.

**Comment by blallen** [comment]
We do something similar with `Array_Type` already, so we can look there to start

**Comment by glwagner** [comment]
If `FT` is enforced by types, we can require all types to define `convert` methods, and use type parameterization hierarchically to make enforcing `FT` easy?
