### ISSUE TITLE
`finalize_atexit` is not supported on Windows

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#75]
I just tried running the rising_thermal_bubble.jl on my windows machine and I'm getting this error:

```
ERROR: LoadError: finalize_atexit is not supported on Windows
```

Maybe we can add a local conditional to handle this (`if Sys.iswindows(); ...; end`).

**Comment by jkozdon** [comment]
Finalize at exit is really needed when you're running in the repl. We could make this change, but then you'd want something like if `Sys.iswindows() && !isinterative(); MPI.Finalize(); end`

**Comment by jkozdon** [comment]
Also, `Sys.iswindows() || MPI.finalize_atexit()` would be more Julian I think

**Comment by jkozdon** [comment]
Take a look at #80
