### ISSUE TITLE
Latest Dycoms in master blows up at 300 s no matter the time step

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#776]
Hi,

The dycoms that was recently corrected to be up-to-date w.r.t. master is blowing up at ~300 s regardless of the time step being used. Something broke it along the way but the amount of changes since when it worked is extremely large.
The reason why the issue was not noticed is because the file used for testing is set up to run only for 100s.

https://github.com/climate-machine/CLIMA/blob/8429c2b88969d1b33f7a76aabace85882038d698/experiments/Atmos_LES/dycoms.jl#L1

Suggestions on how to proceed to find the issue? Way to much was changed since last time this was successfully tested beyond 100 s.

Thanks

**Comment by akshaysridhar** [comment]
What is the exact simulation time to blow-up in your case? 
I attempted to run the driver from the master branch with the following results --

[The only parameter I changed are `FT=Float32` and `timeend=2000s` to speed up the test case: I will run this in Float64 as well] 

`julia --project experiments/Atmos_LES/dycoms.jl --output-dir=dycoms --enable-vtk --vtk-interval=2500` generates the following log
```
┌ Info: Establishing Atmos LES configuration for DYCOMS
│ precision        = Float32
│ polynomial order = 4
│ grid             = 1000x1000x2500
│ resolution       = 40x40x20
└ MPI ranks        = 1
[ Info: Initializing DYCOMS
┌ Info: Starting DYCOMS
│ dt              = 1.63173e-02
│ timeend         = 4.00000e+03
│ number of steps = 245138
└ norm(Q)         = 1.7257589760000000e+09
┌ Info: Diagnostics
└ collecting at 0.0
┌ Info: Update
│ simtime = 2.6891019821166992e+01
│ runtime = 00:00:59
└ norm(Q) = 1.7261940480000000e+09
┌ Info: Update
│ simtime = 9.1752059936523438e+01
│ runtime = 00:01:59
└ norm(Q) = 1.7264707840000000e+09
┌ Info: Update
│ simtime = 1.5688510131835938e+02
│ runtime = 00:02:59
└ norm(Q) = 1.7267100160000000e+09
┌ Info: Diagnostics
└ collecting at 163.16508
┌ Info: Update
│ simtime = 2.2007641601562500e+02
│ runtime = 00:03:59
└ norm(Q) = 1.7269273600000000e+09
┌ Info: Update
│ simtime = 2.8523614501953125e+02
│ runtime = 00:04:59
└ norm(Q) = 1.7271557120000000e+09
┌ Info: Diagnostics
└ collecting at 326.3473
┌ Info: Update
│ simtime = 3.4935189819335938e+02
│ runtime = 00:05:59
└ norm(Q) = 1.7273593600000000e+09
┌ Info: Update
│ simtime = 4.1433297729492188e+02
│ runtime = 00:06:59
└ norm(Q) = 1.7275264000000000e+09
┌ Info: Update
│ simtime = 4.7946099853515625e+02
│ runtime = 00:07:59
└ norm(Q) = 1.7277105920000000e+09
┌ Info: Diagnostics
└ collecting at 489.61633
┌ Info: Update
│ simtime = 5.4355029296875000e+02
│ runtime = 00:08:59
└ norm(Q) = 1.7279118080000000e+09
```

(This is currently still running)

**Comment by smarras79** [comment]
Great, @akshaysridhar  This run helps narrowing the problem down. Mine breaks when I change  `D_subsidence = 0` to `D_subsidence /= 0`

**Comment by smarras79** [comment]
Update after some comparisons (thanks @akshaysridhar for running a test on your end as well):

* The issue is related to using 1 iteration with tolerance 10. 
* There are also two more things that should not be in the dycoms driver but that were not removed from the dycoms in master.
I will close this issue and create a PR with the proper set up.
