### ISSUE TITLE
Move moist tracers 

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#78]
As of now, moist tracers are handled after the dynamics. This should be changed because the moist dynamics depends on R_m, which depends on the values of the moist quantities.

**Comment by jkozdon** [comment]
We'll have to be careful because of the comments in #79, but if this is required we can do that once moist dynamics is implemented.

**Comment by glwagner** [comment]
It may make sense to distinguish between passive and active tracers.

**Comment by jkozdon** [comment]
We do.

[moist loop](https://github.com/climate-machine/CLIMA/blob/5f1226ac5b054fee5dc4cee0e2ecfc5997fb171d/src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations_kernels.jl#L500)
[passive loop](https://github.com/climate-machine/CLIMA/blob/5f1226ac5b054fee5dc4cee0e2ecfc5997fb171d/src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations_kernels.jl#L536)

**Comment by jkozdon** [comment]
We didn't know the details of the moist physics when this was implemented, and we knew that stuff would eventually change, hence the separation.

**Comment by jkozdon** [comment]
One issue that might arise is that we cannot handle register arrays on the GPU right now, so having an arbitrary number of moisture variables might be tough to handle correctly.

**Comment by jkozdon** [comment]
old dycore is going away...
