### ISSUE TITLE
Interpolation fails at Float32 precision

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/CLIMA#783]
Change [this](https://github.com/climate-machine/CLIMA/blob/master/test/Mesh/interpolation.jl#L75) to `Float32` and the brick interpolation test fails. Change [this](https://github.com/climate-machine/CLIMA/blob/master/test/Mesh/interpolation.jl#L176) to `Float32` and the cubed sphere interpolation test fails.

Interpolation must work with either single or double precision.

**Comment by kpamnany** [comment]
Cc: @bischtob

**Comment by simonbyrne** [comment]
We should make sure to run the tests at both precisions.

**Comment by jkozdon** [comment]
The [tolerance](https://github.com/climate-machine/CLIMA/blob/afcc240b63f96a9a5d04d98da7f73e7a838bf9de/test/Mesh/interpolation.jl#L281-L282) is probably set too small for `Float32`.

Also probably want a relative error check, or to use `isapprox` with appropriately chosen `atol` and `rtol`.

In general, based on previous `Float32` problems, I think we need to be careful to build up confidence that the code can be trusted running in `Float32`. We've seen some weirdness before with `Float32` (#505, #713, #669, #81)

**Comment by skandalaCLIMA** [comment]
Yes. Tolerance needs to be increased slightly for Float32 runs. Tests for Float64 and Float32 are now explicitly added. Multiple MPI process runs work fine on the CPU for both Float32 and Float64. It is also tested successfully for both Float32 and Float64 on a single GPU.

I will run these tests on multiple GPUs tomorrow.

**Comment by smarras79** [comment]
Based on what is done in CFD, I would suggest that anything that deals with interpolation and grid generation or adaptivity should be done in Float64 regardless of what precision is used for the calculations.

**Comment by skandalaCLIMA** [comment]
The tests run successfull on 1, 2 & 4 GPUs on the cluster. I believe this resolves the issue.

**Comment by simonbyrne** [comment]
Fixed by #782.
