### ISSUE TITLE
Horizontal diffusion breaks Held-Suarez when using 1DIMEX in default experiment.

### ISSUE THREAD

**Issue by bischtob** [climate-machine/CLIMA#786]
# Description

The Held-Suarez experiment cannot be run when diffusion is applied in the horizontal direction only, even when the diffusion constant is set to zero.

## Steps to reproduce

1. Set time stepper to 1D IMEX with ManyColumnSolver.
2. Set the diffusion direction to `HorizontalDirection()` and run with diffusion like so:
`turbulence = ConstantViscosityWithDivergence(FT(1e5))` for example.
3. Will take about a minute to five minutes on a single GPU.

## Expected behavior

Model is more stable with horizontal diffusion than without due to the stabilizing effects of diffusion. This should not impact time stepping as we are limited by sound waves.

## Environment and Error Messages

NaNs out after a few time steps, aka model blows up without error.

## Additional context

When using 1D IMEX, running Held-Suarez with a "reasonably large" time step given the default grid resolution is not possible. Hence, trying to stabilize the system with horizontal diffusion is a thing to try. This breaks the experiment.

Expectation is to run the default setup with

# For CLIMA developers

- [ ] The bug can be reproduced
- [x] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by tapios** [comment]
When you use horizontal diffusion only, you do not want the divergence term in the viscosity. That term ensure dissipation-free isotropic expansion--makes no sense in 2d.

**Comment by tapios** [comment]
In general, this term is only used for molecular diffusion, generally not in turbulent SGS closures.

**Comment by simonbyrne** [comment]
At the moment, I don’t think the kernels are set up correctly to do gradients in the horizontal direction only. 

@lcw can we discuss this next week?

**Comment by lcw** [comment]
Sure, I need to understand better what terms need to be included for horizontal diffusion.

**Comment by simonbyrne** [comment]
Ah I didn’t realize @mwarusz was already on this.
