### ISSUE TITLE
Remove random perturbation in DYCOMS

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/CLIMA#792]
# Description

Runs should have an option to be reproducible, to aid in debugging. DYCOMS currently triggers turbulent convection with random perturbations in the initial state. There should be a way to choose dynamically that this be done analytically -- it can be done via code like:
```
θ_liq = 0.00232 * sin(x) + 0.0018 * sin(2x) + 0.00052 * cos(x) + θ_liq + 0.0002 * cos(2x)
```
@smarras79 would prefer that we follow [Bryan's definitions](https://www2.mmm.ucar.edu/people/bryan/Code/getperts.html) to trigger a turbulent field that has a pre-defined energy spectrum.

Cc: @simonbyrne @charleskawczynski @bischtob 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by tapios** [comment]
The spectrum of the initial perturbations is irrelevant--the initial condition is forgotten quickly. The perturbations only serve to break the symmetry and hence can be physically insignificantly small. 

Bit-reproducibility may be helpful for debugging. But when we actually use these runs for science, we like the different initial conditions--only the statistics in the end are relevant, and the different initial conditions allow us to sample them in multiple runs.

**Comment by kpamnany** [comment]
Edited the issue to clarify. @tapios -- so you're saying that it's fine to go with @simonbyrne's suggested code above for testing purposes? And that the random perturbations should be retained for true experiment runs?

**Comment by tapios** [comment]
Yes, have an analytical prescription for testing is fine if you guys think that helps.

**Comment by simonbyrne** [comment]
My code above might need some tweaks: for one thing you will probably want to divide `x` and `y`, either by `xmax` or a rough scale value like 100.

**Comment by blallen** [comment]
Has there been any work on this beyond #790?

**Comment by kpamnany** [comment]
No. And BOMEX and Held Suarez also use random perturbations.

One could argue that experiments are not tests and therefore bit reproducibility is not important. Per Tapio's comment, even if we do add an analytical prescription, it should be just for testing which means we have to adjust the experiments to conditionally use randomness.

I'm inclined to close this as not important.
