### ISSUE TITLE
Add `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/CLIMA#794]
# Description

We need a guide for people to make contributions to CLIMA. I liked [libuv's](https://github.com/libuv/libuv/blob/v1.x/CONTRIBUTING.md) guide and suggest using it as a template.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [x] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by leios** [comment]
I agree something like this is needed. The one you linked seems like mainly an intro to git with a link to the style guide.

Can we form a list of things people would need to know (in addition to those listed in the link) to start contributing?

I was hoping to get started on documentation this week, with a "How to contribute" guide being one of the top priorities. I listed more info in the Documentation issue #744.

**Comment by blallen** [comment]
We have one of these now, correct?

**Comment by kpamnany** [comment]
Yep!
