### ISSUE TITLE
Remove hard-coded temperature in AtmosModel `calculate_dt`

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#805]
# Description

A [hard-coded temperature](https://github.com/climate-machine/CLIMA/blob/master/src/Atmos/Model/AtmosModel.jl#L65) exists in AtmosModel. We should change this if/when the Courant functions are ironed out. cc @skandalaCLIMA

## Additional context

I'm not sure if the computed dt is being used but, right now, Dycoms seems to be passing through this function.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by blallen** [comment]
Hi @charleskawczynski , this was always meant to be temporary while we were waiting for the Courant functions to be merged into master. #806 from @jkozdon incorporates those and removes the hardcoding.

**Comment by jkozdon** [comment]
@charleskawczynski Feel free to make suggestions to #806 if you have any. I thought it was odd to, so made a stab at fixing it.

**Comment by jkozdon** [comment]
> Dycoms seems to be passing through this function.

@charleskawczynski What do you mean by this?

**Comment by charleskawczynski** [comment]
> Hi @charleskawczynski , this was always meant to be temporary while we were waiting for the Courant functions to be merged into master. #806 from @jkozdon incorporates those and removes the hardcoding.... @charleskawczynski Feel free to make suggestions to #806 if you have any. I thought it was odd to, so made a stab at fixing it.

I figured it was temporary, I just came across it and wanted to open an issue so that we didn't forget. My apologies, I didn't see that this was being addressed in #806. #806 looks fine to me at first glance!

> @charleskawczynski What do you mean by this?

Just that this function is called when running dycoms (and that it's not an uncalled function).
