### ISSUE TITLE
Make domain extents Float, not Int

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#827]
# Description

The domain extent should be represented in Float64/Float32, not integers. Changes are needed in `AtmosLESConfiguration` and `grid1d`, from what I can tell.

# Additional context

Add any other reasons why this feature will help with the goals of CLIMA.

# For CLIMA Developers

- [x] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
No real objection, but why?

**Comment by smarras79** [comment]
@charleskawczynski by "domain extent" do you mean the domain size or something else?

**Comment by smarras79** [comment]
Comment on precision: even if we run a simulation in Float32, the grid/mesh generation and DG infrastructure (basis functions, etc.) should be always calculated in Float64. Although this may not make a big difference with coarse resolutions, it is likely to impact the results in the regions of fine resolution.

**Comment by akshaysridhar** [comment]
> No real objection, but why?

e.g. for test problems if we want n*pi domains, they wouldn't be supported / user would have to work out where the error is coming from; its an easy enough fix, applied in #842
