### ISSUE TITLE
TKE calculation issue : `AtmosDiagnostics.jl`

### ISSUE THREAD

**Issue by akshaysridhar** [climate-machine/CLIMA#831]
# Description

https://github.com/climate-machine/CLIMA/blob/2959529adf93d652141d9d5b33f504d4a36e5f86/src/Diagnostics/AtmosDiagnostics.jl#L222

This is not consistent, since `MH` is being accounted for twice. This will result in the vars_diagnostic symbol `:TKE` returning **wrong** stuff. @slifer50 could you please confirm and we can fix this :D  

## Steps to reproduce

1. Open output from any LES in `diagnostics*.jld2`.
2. Plot (`(:uvariance + :vvariance + :wvariance) / 2`) and Plot (`:TKE`) 
3. They are not consistent (i.e. order of magnitude), leading to the point about the discrepancy above. 

## Expected behavior

The components listed in 2. should be the approximately the same.

# For CLIMA developers

- [x] The bug can be reproduced
- [x] Labels have been added and developers assigned
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by kpamnany** [comment]
This is now here:

https://github.com/climate-machine/CLIMA/blob/8b113f87308304af2a63c912a5f1af38673c0e77/src/Diagnostics/atmos_default.jl#L256

**Comment by akshaysridhar** [comment]
Thanks @kpamnany :D @slifer50 and I can sort this as part of a set of verification tests against the new b.c. (Unify ATMOS and BOMEX are both good to go so I can use that to stress test the diagnostics module)

**Comment by smarras79** [comment]
> This is now here:
> 
> https://github.com/climate-machine/CLIMA/blob/8b113f87308304af2a63c912a5f1af38673c0e77/src/Diagnostics/atmos_default.jl#L256

There are two error in this calculation: 
* MH should be removed
* The calculation must be square rooted

**Comment by akshaysridhar** [comment]
I've seen RMS velocities used as a diagnostic, but sqrt(TKE) would be unusual(?)

**Comment by smarras79** [comment]
> I've seen RMS velocities used as a diagnostic, but `sqrt(TKE)` would be unusual(?)

Sorry, @akshaysridhar yes, forget what I said. I let me remove that comment in full before people get confused.

**Comment by smarras79** [comment]
This being said, the result of TKE currently returned by the code are incorrect because the `+` should be removed and the calculation should be done out of this loop. The sum is already done when calculating the variances and now we are summing again over TKE.
