### ISSUE TITLE
Diffusive CFL calculator

### ISSUE THREAD

**Issue by akshaysridhar** [climate-machine/CLIMA#844]
# Description

https://github.com/climate-machine/CLIMA/blob/67dc0da452a63147a2980cdc3e7040f36be716f1/src/Atmos/Model/courant.jl#L57

The last argument: should it point to the current time, not `t==0` ? (I'm not sure this currently interacts with the inner code anyway, but if for some reason we had an explicit `t` dependency in the turbulent model this could become problematic)

See `turbulence.jl` for required args in `turbulence_tensors`. Currently this means that the diff CFL is computed based on the first timestep - OK for the constant-visc models, not OK elsewhere (e.g. gradient = 0 at the initial condition, gradient dependent visc == 0 at initial condition) 

## Steps to reproduce
Use ConstantViscosityWithDivergence{FT}(COEFF) on any problem, notice that CFL-diffusive is constant
Use SmagorinskyLilly{FT}(COEFF) or (or any other turn model) : CFL == 0 at ALL times if the velocity gradients are  zero at t== 0. Verifiable with @show statements in turbulence.jl and Model/courant.jl

## Expected behavior

Diff CFL should be time-varying, based on the turbulence model. 

## Screenshots

If applicable, add screenshots to help explain your problem, otherwise please remove this section. This can be particularly useful for physical simulations.

Left-right curves show (high-low) viscous coefficients; demo of one of the visual checks used to verify the viscosity models... ; the issue here appears to be tied to the courant framework 

<img width="400" alt="Screen Shot 2020-03-13 at 3 25 00 PM" src="https://user-images.githubusercontent.com/43710045/76881202-0b941c00-6836-11ea-8308-f1b3dab1bb13.png">

# For CLIMA developers

- [x] The bug can be reproduced
- [x] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by akshaysridhar** [comment]
Determined not to be the root cause. Closing until investigated further.

**Comment by blallen** [comment]
Is this superseded by #950?

**Comment by akshaysridhar** [comment]
Resolved with #950
