### ISSUE TITLE
Fork not in sync with main repo

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#86]
When I `git pull` or `git fetch` from within my fork of `climate-machine/CLIMA` 
git returns `up to date` although I am not. 
In other words, my fork is not in sync with the main code I am forked from.

The log of my fork is:
`commit 5f1226ac5b054fee5dc4cee0e2ecfc5997fb171d (HEAD -> master, origin/master, origin/HEAD)
Merge: db7235e 4adbe39
Author: Lucas C Wilcox <lucas@swirlee.com>
Date:   Thu Feb 21 15:08:42 2019 -0800
`

whereas the log of the main repo is:

`commit 5358a667c357b1b4ab8f273f3edd8e5f873e464a (origin/master, origin/HEAD)
Merge: 5f1226a e23af30
Author: Charles Kawczynski <charliekawczynski@gmail.com>
Date:   Tue Feb 26 13:00:51 2019 -0800
    Merge pull request #80 from jkozdon/windows
    [AtmosDycore] Make drivers windows friendly
`

can anyone please assist on this?
thanks

**Comment by jkozdon** [comment]
github does not automatically sync your forks, you need to do this manually by adding `climate-machine/CLIMA` as a new remote.

See this article: https://help.github.com/en/articles/syncing-a-fork

**Comment by jkozdon** [comment]
Also, make sure you push your changes back to github if you want your github master to be updated as well: https://help.github.com/en/articles/pushing-to-a-remote

**Comment by smarras79** [comment]
> github does not automatically sync your forks, you need to do this manually by adding `climate-machine/CLIMA` as a new remote.
> 
> See this article: https://help.github.com/en/articles/syncing-a-fork

I tried this but things are still considered as `Up to date`

**Comment by smarras79** [comment]
That did it, but I first had to do the following as well:

[https://help.github.com/en/articles/configuring-a-remote-for-a-fork](url)

**Comment by jkozdon** [comment]
Great. I'll close the issue then.
