### ISSUE TITLE
CUDAdrv on OSX

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#87]
Has any of you been successful in building CUDAdrv on a Mac OSX (10.14 Mojave)?
No matter what steps I take, the build fails with 
`Pkg.build("CUDAdrv")
  Building CUDAdrv → `~/.julia/packages/CUDAdrv/LC5XS/deps/build.log`
┌ Error: Error building `CUDAdrv`: 
│ ERROR: LoadError: Initializing CUDA driver failed with code 3.`

(no forum seems to have it solved.)

I am using:
`
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
`
with CUDA Toolkit 10.1 installed.

p.s. For the future, should questions like this one be reported as an Issue?

**Comment by vchuravy** [comment]
That might be https://github.com/JuliaGPU/CUDAapi.jl/issues/66

**Comment by jkozdon** [comment]
Does your mac have an NVIDIA gpu?

**Comment by fxgiraldo** [comment]
Good point. My mac doesn't have an Nvidia GPU and don't think Mac makes any of those anymore.

**Comment by vchuravy** [comment]
You can still attach a NVIDIA GPU as an external GPU. Good point nonetheless

**Comment by jkozdon** [comment]
> p.s. For the future, should questions like this one be reported as an Issue?

I think that this is as reasonable as any of our current options.

**Comment by fxgiraldo** [comment]
On this point,  is there a particular external GPU that someone could recommend? We need to purchase these for each of us at NPS.

**Comment by jkozdon** [comment]
@smarras79 Should this be closed now?

**Comment by smarras79** [comment]
@jkozdon  If I understood well, for now we need to rely on an NVIDIA GPU for this to work. In this case, you can close the issue. Thanks
