### ISSUE TITLE
Should `setup_solver` should be called `SolverConfiguration`?

### ISSUE THREAD

**Issue by glwagner** [climate-machine/CLIMA#872]
# Description

The function `setup_solver` returns an object of type `SolverConfiguration`, and thus appears to be a constructor for `SolverConfiguration`. There does not appear to be a separate interface for instantiating `SolverConfiguration` other than the default constructor.

## Additional context

When attempting to learn how the CLIMA code works and reading `ocean_gyre.jl` script, I was confused at first about the role of the function `setup_solver` and the nature of the object it returned.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by charleskawczynski** [comment]
Agreed. Also, I think there are opportunities to make some variables/functions related to the drivers more descriptive.

**Comment by simonbyrne** [comment]
I would be okay with the change: in general having fewer names is better. @kpamnany is away at the moment, it would be good to hear his thoughts.

**Comment by kpamnany** [comment]
Just for completeness, other things to change:
- `setup_diagnostics()` => `DiagnosticsConfiguration`
- `setup_interpolation()` => `InterpolationConfiguration` (but I think this needs some thought and discussion with @skandalaCLIMA)

Anything else?
