### ISSUE TITLE
Command line arguments for experiments

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/CLIMA#877]
# Description

An experiment should be able to get experiment-specific command line arguments.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by akshaysridhar** [comment]
Ah, awesome, thanks ! To demonstrate how this may be used : `https://github.com/climate-machine/CLIMA/blob/as/hadgem-les/experiments/AtmosLES/cfsites.jl` where currently SLURM_ARRAY is used to grab the experiment specific argument.
