### ISSUE TITLE
EveryXSimulationTime

### ISSUE THREAD

**Issue by kpamnany** [climate-machine/CLIMA#878]
# Description

The implementation for this [is commented out](https://github.com/climate-machine/CLIMA/blob/master/src/ODESolvers/GenericCallbacks.jl#L52-L95). What's the reason for this?

# Additional context

It will be useful to have this interface, esp. for checkpointing.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by kpamnany** [comment]
@jkozdon, @lcw?

**Comment by jkozdon** [comment]
Looking at the git blame, looks like it just never got reenabled after one of our big solver rewrites.
