### ISSUE TITLE
gcm_driver_test.jl takes an hour on Linux on Azure

### ISSUE THREAD

**Issue by blallen** [climate-machine/CLIMA#879]
# Description

See title and discussion on #874. Do we know why it's taking so long?

# For CLIMA developers

- [x] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by blallen** [comment]
@kpamnany any ideas?

**Comment by kpamnany** [comment]
@thomasgibson: is this working as planned or did you intend for this to run on the GPU?

**Comment by thomasgibson** [comment]
This test is meant to run like any other test (see for example, `driver_test.jl`. When I wrote the test, I ran it on CPU and GPU and it did not take 1 hr. Also, keep in mind that CI passed when I made this PR. Did something change or was this issue exposed due to something not being run on CI during the PR process?

I'll see if I can reproduce it.

**Comment by kpamnany** [comment]
The only actual `@test` in this simply verifies that it runs -- it isn't comparing the output against an analytical solution or validating the output in any way. The time cost for this is too high. The test should be either be improved or shortened significantly after which it can be added to SlurmCI (which tests on CPU or GPU or both) or, if shortened, added back to `runtests.jl`.

**Comment by kpamnany** [comment]
I haven't checked to see when this became so slow. It may be due to the KernelAbstractions switch.

Please do check. :)

**Comment by blallen** [comment]
The CI still passes with the current run time... it just takes a really long time to pass

**Comment by kpamnany** [comment]
Yes. CI was well over 3 hours a couple of days ago. #900 helped some, but it's still over 3 hours right now. :( #906 and #907 should get us back down under 2 hours, even with code coverage.

**Comment by thomasgibson** [comment]
Strange. Can't reproduce it locally.
```
Info: Running MPI test...
│   n = 1
│   f = "gcm_driver_test.jl"
└   cmd = `mpiexec --oversubscribe -n 1 /home/thomas/julia-1.3.1/bin/julia -Cnative -J/home/thomas/julia-1.3.1/lib/julia/sys.so -g1 --startup-file=no --project=/home/thomas/src/CLIMA/Project.toml --code-coverage=none /home/thomas/src/CLIMA/test/Driver/gcm_driver_test.jl`
┌ Warning: Your CUDA installation does not provide the CUPTI library, CUDAnative.@code_sass will be unavailable
└ @ CUDAnative ~/.julia/packages/CUDAnative/hfulr/src/CUDAnative.jl:160
┌ Info: Establishing Atmos GCM configuration for GCM Driver test
│ precision        = Float64
│ polynomial order = 4
│ #horiz elems     = 4
│ #vert_elems      = 6
│ domain height    = 1.00e+04
└ MPI ranks        = 1
[ Info: Initializing GCM Driver test
┌ Info: Starting GCM Driver test
│ dt              = 6.00000e+02
│ timeend         =  1800.00
│ number of steps = 3
└ norm(Q)         = 9.5073564673383172e+13
┌ Info: Finished
│ norm(Q)            = 9.5073454082784109e+13
│ norm(Q) / norm(Q₀) = 9.9999883678918067e-01
└ norm(Q) - norm(Q₀) = -1.1059059906250000e+08
┌ Info: Euclidean distance
│ norm(Q - Qe)            = 8.5666522638746557e+09
└ norm(Q - Qe) / norm(Qe) = 9.0105512434551422e-05
 93.686993 seconds (43 allocations: 1.703 KiB)
Test Summary: | Pass  Total
Driver        |    2      2
```
Can anyone else observe it taking hours to run locally?

**Comment by kpamnany** [comment]
Try it on CPU? And then maybe try with code coverage on? That may be the issue.

**Comment by thomasgibson** [comment]
Here's CPU with no code coverage:
```
┌ Info: Establishing Atmos GCM configuration for GCM Driver test
│ precision        = Float64
│ polynomial order = 4
│ #horiz elems     = 4
│ #vert_elems      = 6
│ domain height    = 1.00e+04
└ MPI ranks        = 1
[ Info: Initializing GCM Driver test
┌ Info: Starting GCM Driver test
│ dt              = 6.00000e+02
│ timeend         =  1800.00
│ number of steps = 3
└ norm(Q)         = 9.5073564673382875e+13
┌ Info: Update
│ simtime =  1200.00 /  1800.00
│ runtime = 00:01:09
└ norm(Q) = 9.5073509315790766e+13
┌ Info: Finished
│ norm(Q)            = 9.5073509315790766e+13
│ norm(Q) / norm(Q₀) = 9.9999941773938639e-01
└ norm(Q) - norm(Q₀) = -5.5357592109375000e+07
┌ Info: Euclidean distance
│ norm(Q - Qe)            = 5.0095348190780210e+09
└ norm(Q - Qe) / norm(Qe) = 5.2691143287704111e-05
124.967606 seconds (43 allocations: 1.703 KiB)
```
BUT running `julia --project=@. --code-coverage="user" test/Driver/runtests.jl` (with code-coverage on), it's taking ages locally. I think this is the problem.

**Comment by thomasgibson** [comment]
I think this issue should be reopened. This is still a problem, no?

**Comment by blallen** [comment]
It might be a subset of the great "Code coverage kills performance" issue. Up to you and @kpamnany if we need to keep this one open separately

**Comment by simonbyrne** [comment]
@vchuravy any idea why code coverage is causing these problems?

**Comment by kpamnany** [comment]
This is the same issue underlying #670. I think we only need to leave one open (this issue is now linked to that one).
