### ISSUE TITLE
Locking down the CLIMA repo?

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#9]
At the kick-off meeting we discussed using the github pull request feature exclusively for merging into master. I noticed that right now CLIMA has no protected branches, so anyone on the climate-machine team can write to master, create branches, etc..

I am happy to lock all this down but figured we should discuss this.

One of the major reasons for exclusively using the pull request feature was so that users downstream had a heads up changes were coming and all changes had the opportunity for discussion. Not really a big problem when we have only a few users, but could quickly become a problem as new folks start contributing.

/cc @lcw @charleskawczynski @christophernhill @tapios @adcroft @fxgiraldo

**Comment by tapios** [comment]
Locking down is fine with me.

**Comment by charleskawczynski** [comment]
Fine with me also.

**Comment by jkozdon** [comment]
I've change the permission on master so that no one can push to it directly.

For now I have allowed other branches to be created in CLIMA. We can disable this as well if we only want to have "approved" branches in the CLIMA repo.
