### ISSUE TITLE
size(vgeo) returns 70 elements for a grid of 100 elements

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#91]
In Grid.jl `vgeo` is defined as 

`vgeo = zeros(DFloat, Nq^dim, _nvgeo, nelem)`

In the risiting_thermal_bubble case I am building a 2D grid `Ne = (10,1,10)` for a 2D grid of 100 elements. 
Why does `size(vgeo)` return `nelem = 70`?
Is `vgeo` different from how it was built in `Canary`? I could use vgeo properly in Canary to extract the z coordinates I need.
thanks

**Comment by jkozdon** [comment]
I cannot reproduce what you're talking about. Can you add a minimal code that shows the problem you are experiencing.

**Comment by smarras79** [comment]
@jkozdon  
Modify your `drivers/rising_thermal_bubble.jl' to run in 2d, on CPU, with 10 elements per direction, 
and add the following lines to `Grids.jl --> DiscontinuousSpectralElementGrid()`

`
function DiscontinuousSpectralElementGrid(...)
...
    (vgeo, sgeo) = computegeometry(topology, D, ξ, ω, meshwarp, vmapM)
      Np = (N+1)^dim
      @show("SIZE OF VGEO", size(vgeo))
`
you should see `size(vgeo) = (25, 14, 70)`

**Comment by jkozdon** [comment]
I still cannot reproduce the problem. I'd recommend creating a pull request or branch with the problem are having and we can look at it.

Here is my `git diff` from 

```
❯ git diff
diff --git a/src/ClimaAtmos/Dycore/src/Grids.jl b/src/ClimaAtmos/Dycore/src/Grids.jl
index 79b6222..8af1187 100644
--- a/src/ClimaAtmos/Dycore/src/Grids.jl
+++ b/src/ClimaAtmos/Dycore/src/Grids.jl
@@ -71,6 +71,7 @@ struct DiscontinuousSpectralElementGrid{T, dim, N, Np, DA,
     (vgeo, sgeo) = computegeometry(topology, D, ξ, ω, meshwarp, vmapM)
     Np = (N+1)^dim
     @assert Np == size(vgeo, 1)
+    @show("SIZE OF VGEO", size(vgeo))

      # Create arrays on the device
      vgeo = DeviceArray(vgeo)
```

Here is what happens when I run (truncated output)
```
❯ julia --project drivers/rising_thermal_bubble.jl
"SIZE OF VGEO" = "SIZE OF VGEO"
size(vgeo) = (25, 14, 100)
||Q||₂ (initial) =  2.4158256667836246e+08
```

Not I am working from commit 91e4b4c14db2bd5cfffd80e3621b7eba1dec5895:
```
❯ git rev-parse HEAD

91e4b4c14db2bd5cfffd80e3621b7eba1dec5895
```

**Comment by smarras79** [comment]
A `git fetch upstream` to get back to sync solved it. 
You can close the issue.
Thanks for your help.

**Comment by jkozdon** [comment]
Just an FYI that you can close issues that you opened as well.
