### ISSUE TITLE
conflicting imports related to planet parameters

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#919]
PR #901 seems to have introduced a bunch of `ignoring conflicting import` statements into the tests. See for instance [1].

cc: @charleskawczynski 

[1]: https://gist.github.com/climabot/5f40f182ba6ce220020909b596130403#file-out_9590375-L54-L65

**Comment by charleskawczynski** [comment]
Yeah, sorry about that. I think it's because we can now overload planet parameters, so any tests that share the same namespace may throw warnings :/ I'll look into it either way.

**Comment by charleskawczynski** [comment]
It looks this was fixed by #920
