### ISSUE TITLE
Utilities not precompiled on Caltech GPU 

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#94]
After adding `Utitilies` to the gpu environment on the Caltech GPU, the `MoistThermodynamics` module  is not being found. 

The problem arises when I call any of the functions of moistthermodynamics from Vanilla.
It does not seem tied to MoistThermodynamics, however, it only occurs when I make a call to a MoistThermodynamics function on GPU. 

`ERROR: LoadError: InvalidIRError: compiling knl_volumegrad!(Val{2}, Val{4}, Val{0}, Val{0}, CuDeviceArray{Float64,4,CUDAnative.AS.Global}, CuDeviceArray{Float64,4,CUDAnative.AS.Global}, CuDeviceArray{Float64,4,CUDAnative.AS.Global}, Float64, CuDeviceArray{Float64,2,CUDAnative.AS.Global}, Int64) resulted in invalid LLVM IR
Reason: unsupported call to the Julia runtime (call to jl_get_binding_or_error)
Stacktrace:
 [1] macro expansion at /home/smarras/.julia/packages/CUDAnative/nqSUm/src/device/intrinsics/memory_shared.jl:24
 [2] knl_volumegrad! at /central/home/smarras/climate-machine/CLIMA/src/ClimaAtmos/Dycore/src/VanillaAtmosDiscretizations_cuda.jl:15
Reason: unsupported call to the Julia runtime (call to jl_undefined_var_error)
...`

**Comment by charleskawczynski** [comment]
It's difficult to see where the error is coming from but, I think that it's related to CUDA not supporting intrinsics like `exp` and `log`. See the discussion https://github.com/JuliaGPU/CuArrays.jl/issues/283

**Comment by lcw** [comment]
Hi @smarras79,

Is this still an issue?

**Comment by charleskawczynski** [comment]
Yes, unfortunately. I haven't gotten around to updating #99, which is a step towards fixing this issue.

**Comment by smarras79** [comment]
Hi @lcw  and @charleskawczynski  I am sorry, I haven't gotten to it either.

**Comment by jkozdon** [comment]
@smarras79 Is this still an issue?

**Comment by charleskawczynski** [comment]
@asraero and I discussed this today, and we believe that the GPUifyLoops must be applied to the drivers, not MoistThermodynamics (which operates element-wise).

That said, recent changes in [GPUifyLoops](https://github.com/vchuravy/GPUifyLoops.jl) allow MoistThermodynamics function to be run on the GPU. The example demonstrating this capability is [here](https://github.com/vchuravy/GPUifyLoops.jl/blob/master/examples/contextualize.jl).

I suggest this issue be closed or renamed.
