### ISSUE TITLE
ConstantDiffusionWithDivergence turbulence model creating unphysical heating/cooling.

### ISSUE THREAD

**Issue by slifer50** [climate-machine/CLIMA#948]
# Description

## Additional context

Me and @smarras79 noticed that using the constant diffusion turblence model was making temperature at the boundaries drop or rise in way that are not physics related. When using smagorinsky these issues were no longer present even though it was the same exact test. 
@smarras79 Has suggested this could be happening because the model is creating a thermal boundary layer and that has been an issue in the past. Any insights into this would be appreciated. 

I've attached files for the initial condition for temperature and what happens when using constant diffusion and smagorinsky in that order.1
<img width="332" alt="Screen Shot 2020-04-07 at 2 40 19 PM" src="https://user-images.githubusercontent.com/54990670/78910975-a8239580-7a53-11ea-92b2-103d775891d9.png">
<img width="332" alt="Screen Shot 2020-04-07 at 2 41 12 PM" src="https://user-images.githubusercontent.com/54990670/78910992-aeb20d00-7a53-11ea-8faf-e1c175551c01.png">
<img width="634" alt="Screen Shot 2020-04-09 at 11 33 07 AM" src="https://user-images.githubusercontent.com/54990670/78912715-ede15d80-7a55-11ea-8fc7-350ffb5f4f90.png">

Please note that the highest temperature in the first and third image is approximately 297 K while in the second image it's at 301 and will continue to rise if we run for longer.

This is pretty important as the constant diffusion model is very easily used whenever stability is a concern and is generally useful to let us know if we're on right track for a case before testing other turbulence models.

Branch link: https://github.com/climate-machine/CLIMA/tree/yt/Tropical_cyclone_setup

@yairchn, @tapios, @akshaysridhar, @fxgiraldo. 

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by fxgiraldo** [comment]
@slifer50 can you explain the plot a bit more?  e.g., what is the horizontal axis?  I assume boundary conditions are treated the same in both instances?

**Comment by slifer50** [comment]
The horizontal axis is the z coordinate [0,24000]. Yes the same boundary conditions are applied in both instances with the only sources being gravity, a sponge and Coriolis. FreeSlip, no flux boundaries are used.

**Comment by akshaysridhar** [comment]
What is the value of the constant viscosity for the above plots?

**Comment by slifer50** [comment]
> What is the value of the constant viscosity for the above plots?

200

**Comment by tapios** [comment]
Which thermodynamic variable is being diffused with the constant viscosity?

**Comment by akshaysridhar** [comment]
For reference - here are the results from a +/- 5K potential temperature perturbation about a constant pot-temp background state, running with a constant viscosity coefficient of 50 [Pa.s] for a simulation time of `1000s`. 
<img width="1294" alt="Screen Shot 2020-04-09 at 10 48 45 AM" src="https://user-images.githubusercontent.com/43710045/78927214-5549de00-7a53-11ea-985f-760b3a2e9389.png">
<img width="870" alt="Screen Shot 2020-04-09 at 11 07 34 AM" src="https://user-images.githubusercontent.com/43710045/78927218-57ac3800-7a53-11ea-8b39-f9ac016e02b9.png">

**Comment by tapios** [comment]
@slifer50 Could you please make a plot of total enthalpy per unit mass in the simulation? 

And is the viscosity 200 m^2/s? If the thermal diffusivity is this high and you apply it to energy (or total enthalpy), you'd tend to homogenize the static energy even in the stratosphere, where the stratification is stable. It implies an unphysically strong turbulent mixing in stable stratification--Smagorinsky-Lilly avoids this by limiting the mixing in stable stratification. 

There could also be problems with boundary conditions. A plot of total enthalpy would help see what they are.

**Comment by smarras79** [comment]
@slifer50, what @tapios is describing is what you were seeing yesterday when you showed me the evolution of T with time. You were simply diffusing your heat (nothing else than what you'd expect from the heat equation) with such a large viscosity. 
However, from @akshaysridhar plot, it seems that the thermal b.l. problem that we had in the past has been solved; this may indicate that your ground b.c. mat be not applied correctly. Compare what you are doing at the boundary with what Akshay is doing in his own case of the density current. This should help. However, fixing the top T as you did yesterday fixed the problem on the top, right?

**Comment by slifer50** [comment]
@smarras79 yes if I set a dirichlet at the top the problem at the top doesn't happen. Alternatively using Smagorinsky also solves the problem at the top.

**Comment by slifer50** [comment]
@tapios 
Here is a plot of the initial enthalpy vs enthalpy at 10000 seconds using 200 for constant diffusion. 
<img width="518" alt="Screen Shot 2020-04-10 at 11 49 47 AM" src="https://user-images.githubusercontent.com/54990670/79003864-80026800-7b21-11ea-9a6d-f2957e39efc2.png">

**Comment by tapios** [comment]
Thanks, @slifer50. There's too much enthalpy diffusion in the stratosphere, where the stratification is stable. This large a constant diffusivity in stable stratification just doesn't make sense. Diffusion needs to be limited where stratification limits mixing. We can talk more tomorrow.
