### ISSUE TITLE
Diffusive Courant number callback appears to be broken

### ISSUE THREAD

**Issue by thomasgibson** [climate-machine/CLIMA#950]
# Description

The Courant number callback functionality used in the main driver is broken. The first mistake I found I corrected in the commit: https://github.com/climate-machine/CLIMA/commit/e2c0c010d9e50d78c6197e0ac9ef386093e50110

However, this has revealed another problem. If you run any example in the experiments directory (AtmosLES or AtmosGCM, doesn't matter what you pick) with the Courant number callback turned on, CLIMA crashes.

To see the problem, checkout the branch `thg/broken-courant`.
Here is an example stacktrace (on a CPU) after running: `julia --project=@. experiments/AtmosLES/risingbubble.jl --monitor-courant-numbers --monitor-courant-interval 1`:

```
ERROR: LoadError: TaskFailedException:
MethodError: no method matching norm_ν(::LinearAlgebra.Diagonal{Float64,SArray{Tuple{3},Float64,1,3}}, ::SArray{Tuple{3},Float64,1,3}, ::CLIMA.Mesh.Grids.VerticalDirection)
Closest candidates are:
  norm_ν(!Matched::Real, ::AbstractArray{T,1} where T, ::CLIMA.Mesh.Grids.Direction) at /home/thomas/src/CLIMA/src/Atmos/Model/courant.jl:16
  norm_ν(!Matched::AbstractArray{T,1} where T, ::AbstractArray{T,1} where T, ::CLIMA.Mesh.Grids.VerticalDirection) at /home/thomas/src/CLIMA/src/Atmos/Model/courant.jl:17
  norm_ν(!Matched::AbstractArray{T,1} where T, ::AbstractArray{T,1} where T, ::CLIMA.Mesh.Grids.Direction) at /home/thomas/src/CLIMA/src/Atmos/Model/courant.jl:20
  ...
```

So the problem appears to be related to the lines in `CLIMA/src/Atmos/Model/courant.jl`. It's clear that error is due to the fact that `ν` is actually a matrix, not a vector. So the type dispatch fails. Looking around in `turbulence.jl`, it seems that `ν` is consistently defined as a diagonal matrix. Is this an oversight?

## Steps to reproduce

See description.

## Expected behavior

Should not break.

## Screenshots

If applicable, add screenshots to help explain your problem, otherwise please remove this section. This can be particularly useful for physical simulations.

## Environment and error messages

 - Backtrace of error message
 - Include output of `julia> versioninfo()`

## Additional context

# For CLIMA developers

- [x] The bug can be reproduced
- [x] Labels have been added and developers assigned
- [x] The bug can be fixed (if not, please explain why not in a comment below)
- [x] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by akshaysridhar** [comment]
@thomasgibson The PR that introduces this break is here https://github.com/climate-machine/CLIMA/pull/932 (so yes, this is an oversight that I didn't catch via `runtests.jl`). This can be corrected by addition appropriate type support in the norm_\nu function in `courant.jl`.

**Comment by kpamnany** [comment]
#730 was opened as a reminder that the various callbacks are not exercised in driver tests. And this is another reminder to do so.

**Comment by kpamnany** [comment]
Incidentally, #850 fixes the first mistake as described by Thomas ([here](https://github.com/climate-machine/CLIMA/blob/kp/restart/src/Driver/Driver.jl#L528-L572)).

**Comment by akshaysridhar** [comment]
Fixing in PR#956.
