### ISSUE TITLE
GHA does not post a link to docs preview

### ISSUE THREAD

**Issue by charleskawczynski** [climate-machine/CLIMA#991]
# Description

The docs preview seems to be getting built, but GHA doesn't seem to be commenting links to the preview as expected. For example, see #986, and for the working example, see #953.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by simonbyrne** [comment]
This should have been fixed by #987.

**Comment by charleskawczynski** [comment]
GHA hasn't commented on #993 yet, can we keep this open until we start seeing GHA comment regularly?

**Comment by simonbyrne** [comment]
It doesn't post a comment, it sets a status:
<img width="904" alt="Screen Shot 2020-04-21 at 8 12 16 PM" src="https://user-images.githubusercontent.com/1692009/79936479-75db4600-840c-11ea-9fda-0e21cbb80d0e.png">

**Comment by charleskawczynski** [comment]
Ah, perfect!
