### ISSUE TITLE
Unclear command line options 

### ISSUE THREAD

**Issue by smarras79** [climate-machine/CLIMA#996]
# Description
The command line options in the new master have changed but the help list that is thrown to the user is not self-explanatory. In particular, in the list below, the following keywords need explaination:

`DIAGNOSTICS`
`VTK` 
`MONITOR-TIMESTEP-DURATION` 
`MONITOR-COURANT-NUMBERS`
`CHECKPOINT`
do they indicate time intervals? If so, should they be given in time steps or simulation times?
 
```
unrecognized option --enable-diagnostics
usage: dycoms-test-morediags.jl [--disable-gpu]
                        [--show-updates SHOW-UPDATES]
                        [--diagnostics DIAGNOSTICS] [--vtk VTK]
                        [--monitor-timestep-duration MONITOR-TIMESTEP-DURATION]
                                                [--monitor-courant-numbers MONITOR-COURANT-NUMBERS]
                        [--checkpoint CHECKPOINT]
                        [--checkpoint-keep-all] [--checkpoint-at-end]
                        [--checkpoint-dir CHECKPOINT-DIR]
                        [--restart-from-num RESTART-FROM-NUM]
                        [--log-level LOG-LEVEL]
                        [--output-dir OUTPUT-DIR]
                        [--integration-testing]
```
The wiki explanation should also be updated.

## Additional context

Add any other reasons why this should be addressed.

# For CLIMA Developers

- [ ] This feature can be added (if it cannot be, explain why in a comment below -- lack of technical expertise, not relevant to the scope of this project, too ambitious)
- [ ] There is a timeline for when this feature can be implemented
- [ ] The feature has been (or will be) implemented (Please link the PR)

**Comment by slifer50** [comment]
@smarras79 I second this opinion in particular it's also important to clarify to the user the format of the arguments: as an example --vtk 2000 will give an error of an unrecognized argument type, while the correct format would something like 2000secs or 2000steps, there is no information available at the help level to indicate this rather I had to find it in Callbacks.jl within the Utilities module, it would be useful in general to provide this information to user from the --help

**Comment by akshaysridhar** [comment]
@kpamnany could you please update this with the latest set of command line options - 
https://github.com/climate-machine/CLIMA/wiki/Executing-CLIMA-(with-command-line-arguments)

**Comment by kpamnany** [comment]
See https://github.com/climate-machine/CLIMA/wiki/CLIMA-command-line-arguments

**Comment by smarras79** [comment]
Great, seen and working. Thanks @kpamnany 

I'll close the issue.
